#ifndef SWEETEDITOR_OHOS_LOG_H
#define SWEETEDITOR_OHOS_LOG_H

#include <hilog/log.h>

#undef LOG_DOMAIN
#define LOG_DOMAIN 0xFF00

#define LOGD(...) OH_LOG_Print(LOG_APP, LOG_DEBUG, LOG_DOMAIN, LOG_TAG, __VA_ARGS__)
#define LOGI(...) OH_LOG_Print(LOG_APP, LOG_INFO, LOG_DOMAIN, LOG_TAG, __VA_ARGS__)
#define LOGW(...) OH_LOG_Print(LOG_APP, LOG_WARN, LOG_DOMAIN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_DOMAIN, LOG_TAG, __VA_ARGS__)

#endif //SWEETEDITOR_OHOS_LOG_H
