// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

const _sweeteditorAssetId = 'package:sweeteditor/lib/sweeteditor.dart';

/// Create a Document and return its handle
/// @param text UTF8 text content
/// @return Document handle
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Char>)>(
  assetId: _sweeteditorAssetId,
)
external int create_document_from_utf8(ffi.Pointer<ffi.Char> text);

/// Create a Document and return its handle
/// @param text UTF16 text content
/// @return Document handle
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Uint16>)>(
  assetId: _sweeteditorAssetId,
)
external int create_document_from_utf16(ffi.Pointer<ffi.Uint16> text);

/// Create a Document and return its handle(created from local file)
/// @param path Local file path
/// @return Document handle
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Char>)>(
  assetId: _sweeteditorAssetId,
)
external int create_document_from_file(ffi.Pointer<ffi.Char> path);

/// Free Document
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_document(int document_handle);

/// Get Document UTF8 text
/// @return UTF8 text content
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> get_document_text(int document_handle);

/// Get total line count of Document
/// @return total line count of Document
@ffi.Native<ffi.Size Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int get_document_line_count(int document_handle);

/// Get text of a specific Document line
/// @param line Line number
/// @return UTF16 text content of the specified line
@ffi.Native<ffi.Pointer<ffi.Uint16> Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint16> get_document_line_text(
  int document_handle,
  int line,
);

/// Create EditorCore and return its handle
/// @param measurer Text measurement callback set
/// @param options_data EditorOptions binary payload（LE byte order）:
/// f32 touch_slop         — Move threshold for a tap (default 10)
/// i64 double_tap_timeout — Time window for double tap (default 300ms)
/// i64 long_press_ms      — Long press threshold (default 500ms)
/// f32 fling_friction     — Fling friction coefficient (default 3.5)
/// f32 fling_min_velocity — Minimum fling velocity in px/s (default 50)
/// f32 fling_max_velocity — Maximum fling velocity in px/s (default 8000)
/// u64 max_undo_stack_size — Max undo stack depth, 0=unlimited (default 512)
/// @param options_size Byte length of options_data
/// @return EditorCore handle
@ffi.Native<
  ffi.IntPtr Function(text_measurer_t, ffi.Pointer<ffi.Uint8>, ffi.Size)
>(assetId: _sweeteditorAssetId)
external int create_editor(
  text_measurer_t measurer,
  ffi.Pointer<ffi.Uint8> options_data,
  int options_size,
);

/// Free EditorCore
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_editor(int editor_handle);

/// Load Document
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external void set_editor_document(int editor_handle, int document_handle);

/// Set editor viewport
/// @param width Editor view width
/// @param height Editor view height
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int16, ffi.Int16)>(
  assetId: _sweeteditorAssetId,
)
external void set_editor_viewport(int editor_handle, int width, int height);

/// Notify editor that font metrics have changed (call after font/scale changes)
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_on_font_metrics_changed(int editor_handle);

/// Set fold arrow display mode (affects reserved gutter width)
/// @param mode 0=AUTO(auto show when fold regions exist), 1=ALWAYS(always reserve), 2=HIDDEN(always hide)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_fold_arrow_mode(int editor_handle, int mode);

/// Set auto wrap mode
/// @param mode 0=NONE(no wrap), 1=CHAR_BREAK(character-level wrap), 2=WORD_BREAK(word-level wrap)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_wrap_mode(int editor_handle, int mode);

/// Set tab size (number of spaces per tab stop)
/// @param tab_size Tab size (default 4, minimum 1)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_tab_size(int editor_handle, int tab_size);

/// Set whether Tab inserts spaces instead of a tab character
/// @param enabled 1=enabled, 0=disabled
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_insert_spaces(int editor_handle, int enabled);

/// Set custom key map from binary payload.
/// Payload format (LE byte order):
///   u32 binding_count
///   Repeat binding_count times:
///     u8  first_modifiers
///     u16 first_key_code
///     u8  second_modifiers
///     u16 second_key_code
///     u32 command
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_keymap(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Set editor scale factor
/// @param scale Scale factor (1.0 = 100%)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Float)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_scale(int editor_handle, double scale);

/// Set line spacing parameters (formula: line_height = font_height * mult + add)
/// @param add Extra line spacing in pixels (default 0)
/// @param mult Line spacing multiplier (default 1.0)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Float, ffi.Float)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_line_spacing(
  int editor_handle,
  double add,
  double mult,
);

/// Set extra horizontal padding between gutter split and text content start
/// @param padding Padding in pixels (clamped to >= 0)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Float)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_content_start_padding(
  int editor_handle,
  double padding,
);

/// Set whether to render gutter split line
/// @param show 0=hide, non-zero=show
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_show_split_line(int editor_handle, int show);

/// Set current line render mode
/// @param mode 0=BACKGROUND(fill), 1=BORDER(stroke), 2=NONE(disabled)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_current_line_render_mode(int editor_handle, int mode);

/// Set whether gutter stays fixed during horizontal scroll
/// @param sticky 0=gutter scrolls with content (mobile style), non-zero=gutter fixed (desktop style)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_gutter_sticky(int editor_handle, int sticky);

/// Set whether gutter area is visible
/// @param visible 0=hide entire gutter, non-zero=show gutter
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_gutter_visible(int editor_handle, int visible);

/// Set selection handle hit-test configuration using offset rects
/// @param start_left/start_top/start_right/start_bottom  Start handle hit area offset from cursor bottom anchor (handle tip)
/// @param end_left/end_top/end_right/end_bottom  End handle hit area offset from cursor bottom anchor (handle tip)
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>(assetId: _sweeteditorAssetId)
external void editor_set_handle_config(
  int editor_handle,
  double start_left,
  double start_top,
  double start_right,
  double start_bottom,
  double end_left,
  double end_top,
  double end_right,
  double end_bottom,
);

/// Set scrollbar full configuration (geometry + behavior)
/// @param thickness Scrollbar thickness in pixels
/// @param min_thumb Minimum scrollbar thumb length in pixels
/// @param thumb_hit_padding Extra thumb hit-test padding in pixels
/// @param mode 0=ALWAYS, 1=TRANSIENT, 2=NEVER
/// @param thumb_draggable 1=thumb drag enabled, 0=disabled
/// @param track_tap_mode 0=JUMP, 1=DISABLED
/// @param fade_delay_ms Delay before hide in TRANSIENT mode
/// @param fade_duration_ms Fade duration in TRANSIENT mode (used for both fade-in and fade-out)
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
  )
>(assetId: _sweeteditorAssetId)
external void editor_set_scrollbar_config(
  int editor_handle,
  double thickness,
  double min_thumb,
  double thumb_hit_padding,
  int mode,
  int thumb_draggable,
  int track_tap_mode,
  int fade_delay_ms,
  int fade_duration_ms,
);

/// Build render model for one editor frame
/// @param out_size Output: payload byte length (bytes, excluding extra '\0' terminator)
/// @return EditorRenderModel binary data; payload uses native byte order, and all supported platforms are currently LE.
/// Top-level layout:
/// 1. f32 split_x
/// 2. i32 split_line_visible (0=false, 1=true)
/// 3. f32 scroll_x
/// 4. f32 scroll_y
/// 5. f32 viewport_width
/// 6. f32 viewport_height
/// 7. PointF current_line
/// - f32 x
/// - f32 y
/// 8. i32 current_line_render_mode (0=BACKGROUND, 1=BORDER, 2=NONE)
/// 9. i32 lines_count
/// 10. VisualLine[lines_count] lines
/// VisualLine layout:
/// - i32 logical_line
/// - i32 wrap_index
/// - PointF line_number_position
/// - i32 is_phantom_line
/// - i32 fold_state
/// - i32 run_count
/// - VisualRun[run_count] runs
/// VisualRun layout:
/// - i32 type
/// - f32 x
/// - f32 y
/// - i32 text_utf8_length
/// - u8[text_utf8_length] text_utf8_bytes
/// - TextStyle style
/// - i32 color
/// - i32 background_color
/// - i32 font_style
/// - i32 icon_id
/// - i32 color_value
/// - f32 width
/// - f32 padding
/// - f32 margin
/// 11. i32 gutter_icon_render_count
/// 12. GutterIconRenderItem[gutter_icon_render_count] gutter_icons
/// GutterIconRenderItem layout:
/// - i32 logical_line
/// - i32 icon_id
/// - PointF origin
/// - f32 width
/// - f32 height
/// 13. i32 fold_marker_render_count
/// 14. FoldMarkerRenderItem[fold_marker_render_count] fold_markers
/// FoldMarkerRenderItem layout:
/// - i32 logical_line
/// - i32 fold_state
/// - PointF origin
/// - f32 width
/// - f32 height
/// 15. Cursor cursor
/// - TextPosition text_position
/// - i32 line
/// - i32 column
/// - PointF position
/// - f32 height
/// - i32 visible
/// - i32 show_dragger
/// 16. i32 selection_rect_count
/// 17. SelectionRect[selection_rect_count] selection_rects
/// SelectionRect layout:
/// - PointF origin
/// - f32 width
/// - f32 height
/// 18. SelectionHandle selection_start_handle
/// 19. SelectionHandle selection_end_handle
/// SelectionHandle layout:
/// - PointF position
/// - f32 height
/// - i32 visible
/// 20. CompositionDecoration composition_decoration
/// - i32 active
/// - PointF origin
/// - f32 width
/// - f32 height
/// 21. i32 guide_segment_count
/// 22. GuideSegment[guide_segment_count] guide_segments
/// GuideSegment layout:
/// - i32 direction
/// - i32 type
/// - i32 style
/// - PointF start
/// - PointF end
/// - i32 arrow_end
/// 23. i32 diagnostic_count
/// 24. DiagnosticDecoration[diagnostic_count] diagnostic_decorations
/// DiagnosticDecoration layout:
/// - PointF origin
/// - f32 width
/// - f32 height
/// - i32 severity
/// - i32 color
/// 25. i32 max_gutter_icons
/// 26. i32 linked_editing_rect_count
/// 27. LinkedEditingRect[linked_editing_rect_count] linked_editing_rects
/// LinkedEditingRect layout:
/// - PointF origin
/// - f32 width
/// - f32 height
/// - i32 is_active
/// 28. i32 bracket_highlight_rect_count
/// 29. BracketHighlightRect[bracket_highlight_rect_count] bracket_highlight_rects
/// BracketHighlightRect layout:
/// - PointF origin
/// - f32 width
/// - f32 height
/// 30. (optional append-only tail) ScrollbarModel vertical_scrollbar
/// 31. (optional append-only tail) ScrollbarModel horizontal_scrollbar
/// ScrollbarModel layout:
/// - i32 visible
/// - f32 alpha (0~1)
/// - ScrollbarRect track
/// - ScrollbarRect thumb
/// ScrollbarRect layout:
/// - PointF origin
/// - f32 width
/// - f32 height
/// 32. i32 gutter_sticky (0=scrolls with content, 1=fixed)
/// Call free_binary_data after use; returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> build_editor_render_model(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get editor layout metrics
/// @param out_size Output: payload byte length (bytes, excluding extra '\0' terminator)
/// @return LayoutMetrics binary data; payload uses native byte order, and all supported platforms are currently LE.
/// Top-level layout:
/// 1. f32 font_height
/// 2. f32 font_ascent
/// 3. f32 line_spacing_add
/// 4. f32 line_spacing_mult
/// 5. f32 line_number_margin
/// 6. f32 line_number_width
/// 7. i32 max_gutter_icons
/// 8. f32 inlay_hint_padding
/// 9. f32 inlay_hint_margin
/// 10. i32 fold_arrow_mode (0=AUTO, 1=ALWAYS, 2=HIDDEN)
/// 11. i32 has_fold_regions (0=false, 1=true)
/// Call free_binary_data after use; returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> get_layout_metrics(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// GestureResult binary return layout (payload uses native byte order; all supported platforms are currently LE):
/// 1. i32 gesture_type
/// 2. Only when gesture_type is TAP / DOUBLE_TAP / LONG_PRESS / DRAG_SELECT / CONTEXT_MENU, append:
/// f32 tap_x, f32 tap_y
/// 3. Always append editor state:
/// i32 cursor_line
/// i32 cursor_column
/// i32 has_selection
/// i32 selection_start_line
/// i32 selection_start_column
/// i32 selection_end_line
/// i32 selection_end_column
/// f32 view_scroll_x
/// f32 view_scroll_y
/// f32 view_scale
/// i32 hit_target_type
/// i32 hit_target_line
/// i32 hit_target_column
/// i32 hit_target_icon_id
/// i32 hit_target_color_value
/// i32 needs_edge_scroll (1 = platform should start/continue 16ms timer calling
/// editor_tick_edge_scroll; 0 = platform should stop the timer)
/// i32 needs_fling (1 = platform should start/continue per-frame callback calling
/// editor_tick_fling; 0 = platform should stop the callback)
/// i32 needs_animation (1 = any animation still active; platform can use a single
/// frame callback calling editor_tick_animations instead of separate tick calls)
///
/// Handle gesture event
/// @param type Event type
/// @param pointer_count Finger point count
/// @param points Data for each point
/// @return GestureResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> handle_editor_gesture_event(
  int editor_handle,
  int type,
  int pointer_count,
  ffi.Pointer<ffi.Float> points,
  ffi.Pointer<ffi.Size> out_size,
);

/// Handle gesture event(extended version, supports modifier keys and wheel/scale parameters)
/// @param type Event type
/// @param pointer_count Finger point count
/// @param points Data for each point
/// @param modifiers Modifier key flags(SHIFT=1, CTRL=2, ALT=4, META=8)
/// @param wheel_delta_x Horizontal wheel delta (used for MOUSE_WHEEL/DIRECT_SCROLL)
/// @param wheel_delta_y Vertical wheel delta (used for MOUSE_WHEEL/DIRECT_SCROLL)
/// @param direct_scale Direct scale value (used for DIRECT_SCALE)
/// @return GestureResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Pointer<ffi.Float>,
    ffi.Uint8,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> handle_editor_gesture_event_ex(
  int editor_handle,
  int type,
  int pointer_count,
  ffi.Pointer<ffi.Float> points,
  int modifiers,
  double wheel_delta_x,
  double wheel_delta_y,
  double direct_scale,
  ffi.Pointer<ffi.Size> out_size,
);

/// Tick edge-scroll during drag selection / handle drag.
/// Call at ~16ms intervals while the previous GestureResult.needs_edge_scroll was true.
/// Returns the same GestureResult binary layout as handle_editor_gesture_event.
/// When needs_edge_scroll becomes false in the returned payload, stop the timer.
/// @return GestureResult binary payload
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_tick_edge_scroll(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Tick fling (inertial scroll) animation.
/// Call each frame while the previous GestureResult.needs_fling was true.
/// The core tracks real elapsed time internally; any frame interval is fine.
/// Returns the same GestureResult binary layout as handle_editor_gesture_event.
/// When needs_fling becomes false in the returned payload, stop the timer.
/// @return GestureResult binary payload
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_tick_fling(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Unified animation tick: advances all active animations (edge-scroll, fling).
/// Platform can use a single frame callback driven by needs_animation and call this
/// instead of editor_tick_edge_scroll() / editor_tick_fling() separately.
/// Returns the same GestureResult binary layout as handle_editor_gesture_event.
/// When needs_animation becomes false in the returned payload, stop the callback.
/// @return GestureResult binary payload
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_tick_animations(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// KeyEventResult binary return layout (payload uses native byte order; all supported platforms are currently LE):
/// 1. i32 handled
/// 2. i32 content_changed
/// 3. i32 cursor_changed
/// 4. i32 selection_changed
/// 5. i32 has_edit
/// 6. If has_edit != 0, append a TextEditResult.changes array:
/// i32 change_count
/// Repeat for change_count groups:
/// i32 range_start_line
/// i32 range_start_column
/// i32 range_end_line
/// i32 range_end_column
/// i32 new_text_len
/// u8[new_text_len] new_text_utf8
///
/// Handle keyboard event (optional default key mapping; platform layer can bypass this API and call atomic operation APIs directly)
/// @param key_code Key code (KeyCode enum value)
/// @param text Input text (UTF8; pass for normal character input, pass NULL for special keys)
/// @param modifiers Modifier key flags(SHIFT=1, CTRL=2, ALT=4, META=8)
/// @return KeyEventResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Uint16,
    ffi.Pointer<ffi.Char>,
    ffi.Uint8,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> handle_editor_key_event(
  int editor_handle,
  int key_code,
  ffi.Pointer<ffi.Char> text,
  int modifiers,
  ffi.Pointer<ffi.Size> out_size,
);

/// TextEditResult binary return layout (payload uses native byte order; all supported platforms are currently LE):
/// 1. i32 changed
/// 2. When changed != 0, append change array:
/// i32 change_count
/// Repeat for change_count groups:
/// i32 range_start_line
/// i32 range_start_column
/// i32 range_end_line
/// i32 range_end_column
/// i32 new_text_len
/// u8[new_text_len] new_text_utf8
///
/// Insert text at cursor position (replace selected text if selection exists)
/// @param text UTF8 text to insert
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_insert_text(
  int editor_handle,
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Size> out_size,
);

/// Replace text in the specified range (atomic operation for precise replacements such as textEdit)
/// @param start_line start line of replacement range(0-based)
/// @param start_column Start column of replacement range (0-based)
/// @param end_line end line of replacement range(0-based)
/// @param end_column End column of replacement range (0-based)
/// @param text Replacement UTF8 text
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_replace_text(
  int editor_handle,
  int start_line,
  int start_column,
  int end_line,
  int end_column,
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete text in the specified range
/// @param start_line start line of deletion range(0-based)
/// @param start_column Start column of deletion range (0-based)
/// @param end_line end line of deletion range(0-based)
/// @param end_column End column of deletion range (0-based)
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_delete_text(
  int editor_handle,
  int start_line,
  int start_column,
  int end_line,
  int end_column,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete one character before cursor (Backspace behavior); delete selection if present
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_backspace(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete one character after cursor (Delete behavior); delete selection if present
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_delete_forward(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move current line (or lines covered by selection) up by one line
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_move_line_up(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move current line (or lines covered by selection) down by one line
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_move_line_down(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Copy current line (or lines covered by selection) upward
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_copy_line_up(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Copy current line (or lines covered by selection) downward
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_copy_line_down(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete current line (or all lines covered by selection)
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_delete_line(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Insert empty line above current line
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_insert_line_above(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Insert empty line below current line
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_insert_line_below(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Undo last edit operation
/// @return TextEditResult binary payload, returns NULL when nothing can be undone
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_undo(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Redo last undone operation
/// @return TextEditResult binary payload, returns NULL when nothing can be redone
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_redo(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Whether undo is available
/// @return 1=yes, 0=no
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_can_undo(int editor_handle);

/// Whether redo is available
/// @return 1=yes, 0=no
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_can_redo(int editor_handle);

/// Set cursor position
/// @param line Line number(0-based)
/// @param column Column number (0-based)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Size, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_cursor_position(
  int editor_handle,
  int line,
  int column,
);

/// Get cursor position
/// @param out_line Output: line number
/// @param out_column Output: column number
@ffi.Native<
  ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Size>, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external void editor_get_cursor_position(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_line,
  ffi.Pointer<ffi.Size> out_column,
);

/// Select all
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_select_all(int editor_handle);

/// Set selection range
/// @param start_line selection start line(0-based)
/// @param start_column selection start column (0-based)
/// @param end_line selection end line(0-based)
/// @param end_column selection end column (0-based)
@ffi.Native<
  ffi.Void Function(ffi.IntPtr, ffi.Size, ffi.Size, ffi.Size, ffi.Size)
>(assetId: _sweeteditorAssetId)
external void editor_set_selection(
  int editor_handle,
  int start_line,
  int start_column,
  int end_line,
  int end_column,
);

/// Get current selection range (two cursor positions)
/// @param out_start_line Output: selection start line
/// @param out_start_column Output: selection start column
/// @param out_end_line Output: selection end line
/// @param out_end_column Output: selection end column
/// @return 1=has selection, 0=no selection
@ffi.Native<
  ffi.Int Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external int editor_get_selection(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_start_line,
  ffi.Pointer<ffi.Size> out_start_column,
  ffi.Pointer<ffi.Size> out_end_line,
  ffi.Pointer<ffi.Size> out_end_column,
);

/// Get selected text
/// @return Selected text (UTF8)
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> editor_get_selected_text(int editor_handle);

/// Get text range of word at cursor (scan continuous word chars to the left)
/// @param out_start_line Output: start line
/// @param out_start_column Output: start column
/// @param out_end_line Output: end line
/// @param out_end_column Output: end column
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external void editor_get_word_range_at_cursor(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_start_line,
  ffi.Pointer<ffi.Size> out_start_column,
  ffi.Pointer<ffi.Size> out_end_line,
  ffi.Pointer<ffi.Size> out_end_column,
);

/// Get text content of word at cursor
/// @return Word text (UTF8); returns empty string when cursor is not on a word
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> editor_get_word_at_cursor(int editor_handle);

/// Move cursor left
/// @param extend_selection Whether to extend selection (Shift behavior)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_move_cursor_left(int editor_handle, int extend_selection);

/// Move cursor right
/// @param extend_selection Whether to extend selection
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_move_cursor_right(int editor_handle, int extend_selection);

/// Move cursor up
/// @param extend_selection Whether to extend selection
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_move_cursor_up(int editor_handle, int extend_selection);

/// Move cursor down
/// @param extend_selection Whether to extend selection
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_move_cursor_down(int editor_handle, int extend_selection);

/// Move cursor to line start
/// @param extend_selection Whether to extend selection
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_move_cursor_to_line_start(
  int editor_handle,
  int extend_selection,
);

/// Move cursor to line end
/// @param extend_selection Whether to extend selection
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_move_cursor_to_line_end(
  int editor_handle,
  int extend_selection,
);

/// Notify editor that IME composition starts
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_composition_start(int editor_handle);

/// Update IME composition text
/// @param text Current composition text (UTF8), full composition text each time not incremental
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)>(
  assetId: _sweeteditorAssetId,
)
external void editor_composition_update(
  int editor_handle,
  ffi.Pointer<ffi.Char> text,
);

/// End IME composition and commit final text
/// @param committed_text Final committed text (UTF8); if NULL, use current composition text
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_composition_end(
  int editor_handle,
  ffi.Pointer<ffi.Char> committed_text,
  ffi.Pointer<ffi.Size> out_size,
);

/// Cancel IME composition (do not commit any text)
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_composition_cancel(int editor_handle);

/// Get whether composition is currently active
/// @return 1=composing, 0=not composing
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_is_composing(int editor_handle);

/// Set whether IME composition is enabled
/// @param enabled 1=enabled, 0=disabled
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_composition_enabled(int editor_handle, int enabled);

/// Get whether IME composition is enabled
/// @return 1=enabled, 0=disabled
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_is_composition_enabled(int editor_handle);

/// Set read-only mode
/// @param read_only 1=read-only, 0=editable
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_read_only(int editor_handle, int read_only);

/// Get whether read-only mode is active
/// @return 1=read-only, 0=editable
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_is_read_only(int editor_handle);

/// Set auto indent mode
/// @param mode 0=NONE(no auto indent),1=KEEP_INDENT(keep previous line indent)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_auto_indent_mode(int editor_handle, int mode);

/// Get current auto indent mode
/// @return 0=NONE, 1=KEEP_INDENT
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_get_auto_indent_mode(int editor_handle);

/// Set backspace unindent behavior
/// @param enabled 1=enabled, 0=disabled
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Int)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_backspace_unindent(int editor_handle, int enabled);

/// Scroll to specified line
/// @param line Line number(0-based)
/// @param behavior Scroll behavior(0=GOTO_TOP, 1=GOTO_CENTER, 2=GOTO_BOTTOM)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Size, ffi.Uint8)>(
  assetId: _sweeteditorAssetId,
)
external void editor_scroll_to_line(int editor_handle, int line, int behavior);

/// Go to specified line and column (scroll + cursor positioning)
/// @param line Line number(0-based)
/// @param column Column number (0-based)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Size, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_goto_position(int editor_handle, int line, int column);

/// Adjust scroll offset just enough to keep current cursor visible in viewport
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_ensure_cursor_visible(int editor_handle);

/// Manually set scroll position (automatically clamped to valid range)
/// @param scroll_x Horizontal scroll offset
/// @param scroll_y Vertical scroll offset
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Float, ffi.Float)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_scroll(
  int editor_handle,
  double scroll_x,
  double scroll_y,
);

/// ScrollMetrics binary return layout (payload uses native byte order; all supported platforms are currently LE):
/// 1. f32 scale
/// 2. f32 scroll_x
/// 3. f32 scroll_y
/// 4. f32 max_scroll_x
/// 5. f32 max_scroll_y
/// 6. f32 content_width
/// 7. f32 content_height
/// 8. f32 viewport_width
/// 9. f32 viewport_height
/// 10. f32 text_area_x
/// 11. f32 text_area_width
/// 12. i32 can_scroll_x
/// 13. i32 can_scroll_y
///
/// Get scrollbar metrics
/// @return ScrollMetrics binary payload; Returns default payload for invalid handle
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_get_scroll_metrics(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get screen coordinate rect for any text position (for floating panel positioning)
/// @param line Line number(0-based)
/// @param column Column number (0-based)
/// @param out_x Output: x coordinate in viewport
/// @param out_y Output: y coordinate in viewport (line top)
/// @param out_height Output: line height
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
  )
>(assetId: _sweeteditorAssetId)
external void editor_get_position_rect(
  int editor_handle,
  int line,
  int column,
  ffi.Pointer<ffi.Float> out_x,
  ffi.Pointer<ffi.Float> out_y,
  ffi.Pointer<ffi.Float> out_height,
);

/// Get screen coordinate rect at current cursor position (shortcut)
/// @param out_x Output: x coordinate in viewport
/// @param out_y Output: y coordinate in viewport (line top)
/// @param out_height Output: line height
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
  )
>(assetId: _sweeteditorAssetId)
external void editor_get_cursor_rect(
  int editor_handle,
  ffi.Pointer<ffi.Float> out_x,
  ffi.Pointer<ffi.Float> out_y,
  ffi.Pointer<ffi.Float> out_height,
);

/// Register text style (color + background color + font style)
/// @param style_id Style ID
/// @param color Foreground color value (ARGB)
/// @param background_color Background color value (ARGB), 0 means transparent
/// @param font_style Font style (FontStyle enum value)
@ffi.Native<
  ffi.Void Function(ffi.IntPtr, ffi.Uint32, ffi.Int32, ffi.Int32, ffi.Int32)
>(assetId: _sweeteditorAssetId)
external void editor_register_text_style(
  int editor_handle,
  int style_id,
  int color,
  int background_color,
  int font_style,
);

/// Set style ranges for specified line and layer (compact binary)
/// @param data payload(LE):
/// u32 line, u32 layer, u32 span_count, then repeat for span_count groups
/// [u32 column, u32 length, u32 style_id]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_line_spans(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Batch set highlight spans for multiple lines (compact binary)
/// @param data payload(LE):
/// u32 layer, u32 entry_count,
/// [u32 line, u32 span_count, [u32 column, u32 length, u32 style_id] x span_count] x entry_count
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_batch_line_spans(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Batch register highlight text styles (compact binary)
/// @param data payload(LE):
/// u32 entry_count,
/// [u32 style_id, i32 color, i32 background_color, i32 font_style] x entry_count
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_register_batch_text_styles(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Clear all style ranges for specified line and layer
/// @param line Line number(0-based)
/// @param layer Highlight layer (0=SYNTAX, 1=SEMANTIC)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Size, ffi.Uint8)>(
  assetId: _sweeteditorAssetId,
)
external void editor_clear_line_spans(int editor_handle, int line, int layer);

/// Clear all highlight spans in specified layer
/// @param layer Highlight layer (0=SYNTAX, 1=SEMANTIC)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Uint8)>(
  assetId: _sweeteditorAssetId,
)
external void editor_clear_highlights_layer(int editor_handle, int layer);

/// Set inlay hints for specified line (compact binary, replace whole line)
/// @param data payload(LE):
/// u32 line, u32 hint_count, then repeat for hint_count groups:
/// [u32 type(0=TEXT,1=ICON,2=COLOR), u32 column, i32 int_value(icon_id/color/0),
/// u32 text_len, u8[text_len] text_utf8]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_line_inlay_hints(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Batch set inlay hints for multiple lines (compact binary, variable length)
/// @param data payload(LE):
/// u32 entry_count,
/// [u32 line, u32 hint_count,
/// [u32 type, u32 column, i32 int_value, u32 text_len, u8[text_len] text_utf8] x hint_count] x entry_count
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_batch_line_inlay_hints(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Add one inlay hint (append to specified line, do not replace existing hints)
/// Set phantom texts for specified line (compact binary, replace whole line)
/// @param data payload(LE):
/// u32 line, u32 phantom_count, then repeat for phantom_count groups:
/// [u32 column, u32 text_len, u8[text_len] text_utf8]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_line_phantom_texts(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Batch set phantom texts for multiple lines (compact binary, variable length)
/// @param data payload(LE):
/// u32 entry_count,
/// [u32 line, u32 phantom_count,
/// [u32 column, u32 text_len, u8[text_len] text_utf8] x phantom_count] x entry_count
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_batch_line_phantom_texts(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Set gutter icons for specified line (compact binary, replace whole line)
/// @param data payload(LE):
/// u32 line, u32 icon_count, then repeat for icon_count groups
/// [i32 icon_id]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_line_gutter_icons(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Batch set gutter icons for multiple lines (compact binary, fixed length)
/// @param data payload(LE):
/// u32 entry_count,
/// [u32 line, u32 icon_count, [i32 icon_id] x icon_count] x entry_count
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_batch_line_gutter_icons(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Set max gutter icon count (affects reserved gutter width)
/// @param count Max icon count (0=no reserved space)
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Uint32)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_max_gutter_icons(int editor_handle, int count);

/// Clear all gutter icons
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_gutter_icons(int editor_handle);

/// Set diagnostic decoration ranges for specified line (compact binary)
/// @param data payload(LE):
/// u32 line, u32 diag_count, then repeat for diag_count groups
/// [u32 column, u32 length, i32 severity, i32 color]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_line_diagnostics(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Batch set diagnostic decorations for multiple lines (compact binary, fixed length)
/// @param data payload(LE):
/// u32 entry_count,
/// [u32 line, u32 diag_count, [u32 column, u32 length, i32 severity, i32 color] x diag_count] x entry_count
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_batch_line_diagnostics(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Clear all diagnostic decorations
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_diagnostics(int editor_handle);

/// Set indent guide list (compact binary, global replace)
/// @param data payload(LE):
/// u32 count, then repeat count groups
/// [u32 start_line, u32 start_column, u32 end_line, u32 end_column]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_indent_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Set bracket branch guide list (compact binary, global replace)
/// @param data payload(LE):
/// u32 count, then repeat count groups:
/// [u32 parent_line, u32 parent_column, u32 end_line, u32 end_column,
/// u32 child_count, then repeat child_count groups: [u32 child_line, u32 child_column]]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_bracket_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Set control-flow back-arrow guide list (compact binary, global replace)
/// @param data payload(LE):
/// u32 count, then repeat count groups
/// [u32 start_line, u32 start_column, u32 end_line, u32 end_column]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_flow_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Set horizontal separator guide list (compact binary, global replace)
/// @param data payload(LE):
/// u32 count, then repeat count groups
/// [i32 line, i32 style, i32 count, u32 text_end_column]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_separator_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Clear all code structure lines (indent guides, bracket guides, control-flow arrows, separators)
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_guides(int editor_handle);

/// Set bracket pair list (override default (){}[])
/// @param open_chars Open bracket char array (UTF-32)
/// @param close_chars Close bracket char array (UTF-32)
/// @param count Bracket pair count
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Size,
  )
>(assetId: _sweeteditorAssetId)
external void editor_set_bracket_pairs(
  int editor_handle,
  ffi.Pointer<ffi.Uint32> open_chars,
  ffi.Pointer<ffi.Uint32> close_chars,
  int count,
);

/// Set auto-closing bracket pair list used by automatic pair insertion/deletion
/// @param open_chars Open bracket char array (UTF-32)
/// @param close_chars Close bracket char array (UTF-32)
/// @param count Bracket pair count
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Size,
  )
>(assetId: _sweeteditorAssetId)
external void editor_set_auto_closing_pairs(
  int editor_handle,
  ffi.Pointer<ffi.Uint32> open_chars,
  ffi.Pointer<ffi.Uint32> close_chars,
  int count,
);

/// Externally set exact bracket match result (override built-in char scan)
/// @param open_line open bracket line number(0-based)
/// @param open_col open bracket column number (0-based)
/// @param close_line close bracket line number(0-based)
/// @param close_col close bracket column number (0-based)
@ffi.Native<
  ffi.Void Function(ffi.IntPtr, ffi.Size, ffi.Size, ffi.Size, ffi.Size)
>(assetId: _sweeteditorAssetId)
external void editor_set_matched_brackets(
  int editor_handle,
  int open_line,
  int open_col,
  int close_line,
  int close_col,
);

/// Clear externally set bracket match result (fall back to built-in char scan)
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_matched_brackets(int editor_handle);

/// Set foldable region list (compact binary)
/// @param data payload(LE):
/// u32 region_count, then repeat for region_count groups
/// [u32 start_line, u32 end_line]
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_set_fold_regions(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Toggle fold state of specified line
/// @param line Line number(0-based)
/// @return 1=found and toggled, 0=region not found
@ffi.Native<ffi.Int Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external int editor_toggle_fold(int editor_handle, int line);

/// Fold region containing specified line
/// @param line Line number(0-based)
/// @return 1=success, 0=not found
@ffi.Native<ffi.Int Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external int editor_fold_at(int editor_handle, int line);

/// Unfold region containing specified line
/// @param line Line number(0-based)
/// @return 1=success, 0=not found
@ffi.Native<ffi.Int Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external int editor_unfold_at(int editor_handle, int line);

/// Fold all regions
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_fold_all(int editor_handle);

/// Unfold all regions
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_unfold_all(int editor_handle);

/// Check whether specified line is visible (not hidden by folding)
/// @param line Line number(0-based)
/// @return 1=visible, 0=hidden
@ffi.Native<ffi.Int Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external int editor_is_line_visible(int editor_handle, int line);

/// Clear all highlight spans
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_highlights(int editor_handle);

/// Clear all inlay hints
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_inlay_hints(int editor_handle);

/// Clear all phantom texts
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_phantom_texts(int editor_handle);

/// Clear all decoration data
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_clear_all_decorations(int editor_handle);

/// Insert VSCode snippet template and enter linked editing mode (convenience API)
/// @param snippet_template VSCode snippet template (UTF8)
/// @return TextEditResult binary payload, returns NULL if there is no change
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_insert_snippet(
  int editor_handle,
  ffi.Pointer<ffi.Char> snippet_template,
  ffi.Pointer<ffi.Size> out_size,
);

/// Start linked editing mode with generic LinkedEditingModel (compact binary)
/// @param data payload(LE):
/// u32 group_count, u32 range_count, u32 string_blob_size
/// group_count groups: [u32 index, u32 default_text_offset, u32 default_text_len]
/// range_count groups: [u32 group_ordinal, u32 start_line, u32 start_col, u32 end_line, u32 end_col]
/// UTF-8 string blob(default_text_offset=0xFFFFFFFF means null)
/// @param size payload byte length
@ffi.Native<ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external void editor_start_linked_editing(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Whether linked editing mode is active
/// @return 1=yes, 0=no
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_is_in_linked_editing(int editor_handle);

/// Linked editing: jump to next tab stop
/// @return 1=jumped successfully, 0=already at end (session ends automatically)
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_linked_editing_next(int editor_handle);

/// Linked editing: jump to previous tab stop
/// @return 1=jumped successfully, 0=already at first
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_linked_editing_prev(int editor_handle);

/// Cancel linked editing mode
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void editor_cancel_linked_editing(int editor_handle);

/// Free string memory allocated on C++ side
/// @param string_ptr String pointer
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_u16_string(int string_ptr);

/// Free binary memory returned by C++ side
/// Applies to all APIs that return const uint8_t* + out_size.
/// Platform must call once after reading payload; NULL/0 can be safely ignored.
/// @param data_ptr Start address of binary payload
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_binary_data(int data_ptr);

/// Text measurement callback set, passed when creating EditorCore
final class text_measurer_t extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Float Function(ffi.Pointer<ffi.Uint16> text, ffi.Int32 font_style)
    >
  >
  measure_text_width;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Float Function(ffi.Pointer<ffi.Uint16> text)>
  >
  measure_inlay_hint_width;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Float Function(ffi.Int32 icon_id)>
  >
  measure_icon_width;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Float> arr, ffi.Size length)
    >
  >
  get_font_metrics;
}
