using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Shapes;
using Avalonia.Controls.Templates;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;
using Avalonia.Threading;
using SweetEditor;
using SweetEditor.Avalonia.Demo.Decoration;
using SweetEditor.Avalonia.Demo.Editor;
using SweetEditor.Avalonia.Demo.Host;
using SweetEditor.Avalonia.Demo.UI;
using SweetEditor.Avalonia.Demo.UI.Samples;
using SweetEditor.Avalonia.Demo.UI.Toolbar;
using SweetEditor.Avalonia.Demo.ViewModels;
using AvaControls = global::Avalonia.Controls;
using AvaInteractivity = global::Avalonia.Interactivity;
using AvaPath = global::Avalonia.Controls.Shapes.Path;

namespace SweetEditor.Avalonia.Demo;

public sealed class MainView : UserControl
{
    [Flags]
    private enum DeferredChromeWork
    {
        None = 0,
        Summary = 1 << 0,
        CompletionPopup = 1 << 1,
        SelectionActionBar = 1 << 2,
        CursorVisibility = 1 << 3,
        SamplePickerPopup = 1 << 4,
    }

    private static readonly float[] ScalePresets = { 0.72f, 0.82f, 0.90f, 0.96f, 1.08f, 1.20f };
    private const double CompletionRowHeight = 32;
    private const int CompletionMaxVisibleItems = 6;
    private const double CompletionPopupWidth = 300;
    private const double CompletionPopupMinWidth = 160;
    private const double SamplePickerPopupMaxHeight = 320;
    private const double SelectionActionBarMinWidth = 180;
    private const double SelectionActionBarVerticalOffset = 8;
    private const int SelectionActionAnchorRetentionMs = 1800;
    private const string InlineSuggestionText =
        "\nvoid autoGenerated() {\n    std::cout << \"hello\" << std::endl;\n    return;\n}";

    private const string LinkedSnippet =
        "for (int ${1:i} = 0; ${1:i} < ${2:count}; ++${1:i})\n" +
        "{\n" +
        "    ${0:// body}\n" +
        "}";

    private readonly SweetEditorController controller = new();
    private SweetEditorControl? editor;
    private readonly TextBlock statusText = new();
    private readonly TextBlock summaryText = new();
    private readonly Grid layoutRoot = new();
    private readonly Border toolbarContainer = new();
    private readonly Border statusBar = new();
    private readonly Grid editorHost = new();
    private readonly Border samplePickerPopup = new();
    private readonly Border completionPopup = new();
    private readonly Border selectionActionBar = new();
    private readonly ScrollViewer samplePickerScrollViewer = new();
    private readonly ScrollViewer completionScrollViewer = new();
    private readonly ScrollViewer selectionActionScrollViewer = new();
    private readonly StackPanel samplePickerItemsPanel = new();
    private readonly StackPanel completionItemsPanel = new();
    private readonly StackPanel selectionActionItemsPanel = new();

    private readonly MainViewModel viewModel;
    private readonly Border welcomeOverlay = new();
    private readonly LoadingIndicator loadingIndicator = new();
    private readonly NotificationPanel notificationPanel = new();

    private readonly DemoDecorationProvider decorationProvider;
    private readonly DemoCompletionProvider completionProvider = new();
    private readonly DemoIconProvider iconProvider = new();
    private readonly DemoSelectionMenuItemProvider selectionMenuProvider;
    private readonly DemoNewLineActionProvider newLineActionProvider = new();
    private readonly EditorToolbarController toolbarController = new();
    private readonly SampleDocumentLoader sampleLoader;

    private readonly List<CompletionItem> currentCompletionItems = new();

    private DemoSampleFile? activeSample;
    private string currentLanguageId = "plaintext";
    private bool darkTheme = true;
    private bool perfOverlayEnabled;
    private bool useVsCodeKeyMap = true;
    private bool inlineSuggestionAutoEnabled = true;
    private bool allowPassiveInlineSuggestion;
    private bool foldCollapsed;
    private WrapMode wrapMode = WrapMode.NONE;
    private float currentScale = 1f;
    private int selectedCompletionIndex = -1;
    private DeferredChromeWork pendingChromeWork;
    private int pendingInlineSuggestionToken;
    private int pendingSelectionActionBarRefreshToken;
    private bool chromeRefreshScheduled;
    private bool editorInitializationScheduled;
    private bool demoInitialized;
    private SelectionActionAnchorSnapshot? recentSelectionActionAnchor;
    private long recentSelectionActionAnchorTickMs;
    private string? lastSummaryValue;
    private string? selectionActionBarItemsSignature;

    public MainView()
    {
        viewModel = new MainViewModel();
        viewModel.SaveSettingsRequested += () => viewModel.SaveCurrentSettings();

        decorationProvider = new DemoDecorationProvider(() => controller.GetDocument(), controller.RequestDecorationRefresh);
        selectionMenuProvider = new DemoSelectionMenuItemProvider(
            () => inlineSuggestionAutoEnabled,
            () => perfOverlayEnabled,
            () => useVsCodeKeyMap);
        sampleLoader = new SampleDocumentLoader(
            controller,
            decorationProvider,
            toolbarController.FileCombo,
            UpdateStatus,
            ApplyLanguageConfiguration,
            PrepareForSampleLoad,
            toolbarController.SetSamplePickerEnabled);
        decorationProvider.HighlightBackendChanged += () =>
            Dispatcher.UIThread.Post(() => ScheduleChromeRefresh(DeferredChromeWork.Summary), DispatcherPriority.Background);

        ApplyViewModelSettings();
        BuildLayout();
        WireEvents();
        SetupWelcomeOverlay();

        ScheduleEditorInitialization();
    }

    private void ApplyViewModelSettings()
    {
        DemoSettings settings = viewModel.GetSettings();
        darkTheme = settings.DarkTheme;
        wrapMode = settings.WrapMode;
        currentScale = settings.CurrentScale > 0 ? settings.CurrentScale : 1f;
        perfOverlayEnabled = settings.PerfOverlayEnabled;
        useVsCodeKeyMap = settings.UseVsCodeKeyMap;
        inlineSuggestionAutoEnabled = settings.InlineSuggestionAutoEnabled;
    }

    private void SetupWelcomeOverlay()
    {
        WelcomeOverlayView welcomeView = new();
        welcomeView.CloseRequested += () =>
        {
            welcomeOverlay.IsVisible = false;
            viewModel.ShowWelcome = false;
            editor?.Focus();
        };
        welcomeView.DontShowAgainRequested += () =>
        {
            viewModel.ShowWelcome = false;
        };

        welcomeOverlay.Background = Brushes.Transparent;
        welcomeOverlay.HorizontalAlignment = HorizontalAlignment.Stretch;
        welcomeOverlay.VerticalAlignment = VerticalAlignment.Stretch;
        welcomeOverlay.ZIndex = 80;
        welcomeOverlay.Child = welcomeView;
        welcomeOverlay.IsVisible = viewModel.ShowWelcome;
    }

    private void BuildLayout()
    {
        toolbarContainer.BorderThickness = new Thickness(0, 0, 0, 1);
        toolbarContainer.Padding = new Thickness(6, 4, 3, 4);
        toolbarContainer.Child = toolbarController.BuildView();

        samplePickerItemsPanel.Spacing = 2;
        samplePickerScrollViewer.Content = samplePickerItemsPanel;
        samplePickerScrollViewer.HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled;
        samplePickerScrollViewer.VerticalScrollBarVisibility = ScrollBarVisibility.Auto;

        samplePickerPopup.Child = samplePickerScrollViewer;
        samplePickerPopup.IsVisible = false;
        samplePickerPopup.Padding = new Thickness(4);
        samplePickerPopup.CornerRadius = new CornerRadius(12);
        samplePickerPopup.BorderThickness = new Thickness(1);
        samplePickerPopup.HorizontalAlignment = HorizontalAlignment.Left;
        samplePickerPopup.VerticalAlignment = VerticalAlignment.Top;
        samplePickerPopup.ZIndex = 70;

        completionItemsPanel.Spacing = 0;
        completionScrollViewer.Content = completionItemsPanel;
        completionScrollViewer.HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled;
        completionScrollViewer.VerticalScrollBarVisibility = ScrollBarVisibility.Hidden;

        completionPopup.Child = completionScrollViewer;
        completionPopup.IsVisible = false;
        completionPopup.Padding = new Thickness(4, 6);
        completionPopup.CornerRadius = new CornerRadius(12);
        completionPopup.BorderThickness = new Thickness(1);
        completionPopup.HorizontalAlignment = HorizontalAlignment.Left;
        completionPopup.VerticalAlignment = VerticalAlignment.Top;
        completionPopup.ZIndex = 40;
        completionPopup.MaxWidth = CompletionPopupWidth;

        selectionActionItemsPanel.Orientation = Orientation.Horizontal;
        selectionActionItemsPanel.Spacing = 4;
        selectionActionScrollViewer.Content = selectionActionItemsPanel;
        selectionActionScrollViewer.HorizontalScrollBarVisibility = ScrollBarVisibility.Auto;
        selectionActionScrollViewer.VerticalScrollBarVisibility = ScrollBarVisibility.Hidden;
        selectionActionScrollViewer.HorizontalAlignment = HorizontalAlignment.Stretch;

        selectionActionBar.Child = selectionActionScrollViewer;
        selectionActionBar.IsVisible = false;
        selectionActionBar.Padding = new Thickness(6);
        selectionActionBar.CornerRadius = new CornerRadius(12);
        selectionActionBar.BorderThickness = new Thickness(1);
        selectionActionBar.HorizontalAlignment = HorizontalAlignment.Left;
        selectionActionBar.VerticalAlignment = VerticalAlignment.Top;
        selectionActionBar.ZIndex = 50;

        editorHost.Children.Add(completionPopup);
        editorHost.Children.Add(selectionActionBar);

        loadingIndicator.IsLoading = false;
        loadingIndicator.LoadingText = "Loading sample...";
        loadingIndicator.ZIndex = 60;
        editorHost.Children.Add(loadingIndicator);

        notificationPanel.DarkTheme = darkTheme;
        notificationPanel.ZIndex = 90;
        editorHost.Children.Add(notificationPanel);

        statusText.Text = "Ready";
        statusText.FontSize = 11.5;
        statusText.TextTrimming = TextTrimming.CharacterEllipsis;
        summaryText.FontSize = 10.5;
        summaryText.TextTrimming = TextTrimming.CharacterEllipsis;
        summaryText.TextAlignment = TextAlignment.Right;
        summaryText.HorizontalAlignment = HorizontalAlignment.Right;

        Grid statusPanel = new()
        {
            ColumnDefinitions = new ColumnDefinitions("*,Auto"),
            Margin = new Thickness(8, 4, 8, 5),
            ColumnSpacing = 8,
            Children =
            {
                statusText,
            },
        };
        Grid.SetColumn(summaryText, 1);
        statusPanel.Children.Add(summaryText);

        statusBar.BorderThickness = new Thickness(0, 1, 0, 0);
        statusBar.Child = statusPanel;

        layoutRoot.RowDefinitions = new RowDefinitions("Auto,*,Auto");
        Grid.SetRow(toolbarContainer, 0);
        Grid.SetRow(editorHost, 1);
        Grid.SetRow(statusBar, 2);
        Grid.SetRowSpan(samplePickerPopup, 3);
        Grid.SetRowSpan(welcomeOverlay, 3);
        layoutRoot.Children.Add(toolbarContainer);
        layoutRoot.Children.Add(editorHost);
        layoutRoot.Children.Add(statusBar);
        layoutRoot.Children.Add(samplePickerPopup);
        layoutRoot.Children.Add(welcomeOverlay);
        Content = layoutRoot;
    }

    private void WireEvents()
    {
        toolbarController.SamplePickerButton.Click += (_, _) => ToggleSamplePickerPopup();
        toolbarController.FileCombo.SelectionChanged += async (_, _) =>
        {
            SyncSamplePickerSelection();
            await sampleLoader.OnSelectedSampleChangedAsync().ConfigureAwait(false);
        };
        toolbarController.UndoButton.Click += (_, _) => ExecuteAction(controller.Undo(), "Undo", "Nothing to undo");
        toolbarController.RedoButton.Click += (_, _) => ExecuteAction(controller.Redo(), "Redo", "Nothing to redo");
        toolbarController.ThemeButton.Click += (_, _) => ToggleTheme();
        toolbarController.WrapButton.Click += (_, _) => CycleWrapMode();
        toolbarController.ZoomOutButton.Click += (_, _) => StepScale(-1);
        toolbarController.ZoomInButton.Click += (_, _) => StepScale(1);
        toolbarController.PerfButton.Click += (_, _) => TogglePerfOverlay();
        toolbarController.HelpButton.Click += (_, _) => ShowKeyboardShortcutsDialog();

        controller.DocumentLoaded += (_, _) =>
        {
            foldCollapsed = false;
            allowPassiveInlineSuggestion = false;
            recentSelectionActionAnchor = null;
            RefreshActionState();
            UpdateStatus(activeSample != null ? $"Loaded: {activeSample.FileName}" : "Document loaded");
            UpdateFeatureStrip();
            ScheduleChromeRefresh(DeferredChromeWork.Summary | DeferredChromeWork.SelectionActionBar);
        };

        controller.TextChanged += (_, e) =>
        {
            allowPassiveInlineSuggestion = true;
            recentSelectionActionAnchor = null;
            CancelPendingInlineSuggestion();
            RefreshActionState();
            ScheduleChromeRefresh(DeferredChromeWork.Summary | DeferredChromeWork.SelectionActionBar);
        };

        controller.CursorChanged += (_, e) =>
        {
            DeferredChromeWork work = DeferredChromeWork.Summary | DeferredChromeWork.CompletionPopup;
            if (IsImeVisibleInEditorHost())
                work |= DeferredChromeWork.CursorVisibility;
            if (selectionActionBar.IsVisible || controller.IsInlineSuggestionShowing() || IsRecentSelectionActionAnchorAvailable())
                work |= DeferredChromeWork.SelectionActionBar;
            ScheduleChromeRefresh(work);
            MaybeShowInlineSuggestion(e.CursorPosition);
        };

        controller.SelectionChanged += (_, e) =>
        {
            if (e.HasSelection && ShouldPreferGestureOnlySelectionAnchor())
                CaptureSelectionActionAnchor(null, e.CursorPosition);
            else
                CaptureSelectionActionAnchor(e.HasSelection ? e.Selection : null, e.CursorPosition);
            CancelPendingInlineSuggestion();
            if (ShouldDeferLargeDocumentUiRefresh())
            {
                Dispatcher.UIThread.Post(() =>
                {
                    DeferredChromeWork work = DeferredChromeWork.Summary | DeferredChromeWork.SelectionActionBar;
                    if (IsImeVisibleInEditorHost())
                        work |= DeferredChromeWork.CursorVisibility;
                    ScheduleChromeRefresh(work);
                    RefreshSelectionActionBarWithStabilization();
                }, DispatcherPriority.Background);
            }
            else
            {
                DeferredChromeWork work = DeferredChromeWork.Summary | DeferredChromeWork.SelectionActionBar;
                if (IsImeVisibleInEditorHost())
                    work |= DeferredChromeWork.CursorVisibility;
                ScheduleChromeRefresh(work);
                RefreshSelectionActionBarWithStabilization();
            }
        };

        controller.ScrollChanged += (_, _) =>
        {
            DeferredChromeWork work = DeferredChromeWork.None;
            if (completionPopup.IsVisible)
                work |= DeferredChromeWork.CompletionPopup;
            if (selectionActionBar.IsVisible || controller.IsInlineSuggestionShowing() || IsRecentSelectionActionAnchorAvailable())
                work |= DeferredChromeWork.SelectionActionBar;
            if (work != DeferredChromeWork.None)
                ScheduleChromeRefresh(work);
        };

        controller.ScaleChanged += (_, e) =>
        {
            currentScale = e.Scale;
            RefreshActionState();
            UpdateStatus($"Scale: {e.Scale * 100:F0}%");
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        };
        controller.LongPress += (_, e) =>
        {
            (bool hasSelection, TextRange range) = controller.GetSelection();
            if (hasSelection)
                CaptureSelectionActionAnchor(range, e.CursorPosition, e.ScreenPoint);
            else
                CaptureSelectionActionAnchor(null, e.CursorPosition, e.ScreenPoint);
            UpdateStatus($"Long press: {e.ScreenPoint.X:F0},{e.ScreenPoint.Y:F0}");
            Dispatcher.UIThread.Post(
                () => RefreshSelectionActionBarWithStabilization(forceRetry: IsImeVisibleInEditorHost()),
                DispatcherPriority.Background);
        };
        controller.DoubleTap += (_, e) =>
        {
            if (e.HasSelection && e.Selection is TextRange selection)
                CaptureSelectionActionAnchor(selection, e.CursorPosition, e.ScreenPoint);
            else
                CaptureSelectionActionAnchor(null, e.CursorPosition, e.ScreenPoint);
            UpdateStatus($"Double tap: {e.ScreenPoint.X:F0},{e.ScreenPoint.Y:F0}");
            Dispatcher.UIThread.Post(
                () => RefreshSelectionActionBarWithStabilization(forceRetry: IsImeVisibleInEditorHost()),
                DispatcherPriority.Background);
        };
        controller.ContextMenu += (_, _) => UpdateStatus("Context menu requested");
        controller.GutterIconClick += (_, e) => UpdateStatus($"Gutter icon at line {e.Line}");
        controller.FoldToggle += (_, e) =>
        {
            foldCollapsed = !controller.IsLineVisible(e.Line + 1);
            UpdateStatus($"Fold toggled at line {e.Line} ({(e.IsGutter ? "gutter" : "placeholder")})");
            UpdateFeatureStrip();
        };
        controller.InlayHintClick += (_, e) =>
        {
            if (e.Type == InlayType.Color)
                UpdateStatus($"Color inlay clicked: 0x{e.IntValue:X8}");
            else if (e.Type == InlayType.Icon)
                UpdateStatus($"Icon inlay clicked: {e.IntValue}");
            else
                UpdateStatus($"Inlay clicked at {e.Line}:{e.Column}");
        };
        controller.CompletionItemsUpdated += items =>
        {
            Dispatcher.UIThread.Post(() => ShowCompletionItems(items));
        };
        controller.CompletionDismissed += () => Dispatcher.UIThread.Post(() =>
        {
            HideCompletionPopup();
            MaybeShowInlineSuggestion(controller.GetCursorPosition());
            UpdateFeatureStrip();
        });
        controller.InlineSuggestionAccepted += suggestion =>
        {
            CancelPendingInlineSuggestion();
            UpdateStatus($"Ghost accepted at {suggestion.Line}:{suggestion.Column}");
            ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar);
        };
        controller.InlineSuggestionDismissed += suggestion =>
        {
            CancelPendingInlineSuggestion();
            UpdateStatus($"Ghost dismissed at {suggestion.Line}:{suggestion.Column}");
            ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar);
        };

        AddHandler(InputElement.PointerPressedEvent, OnMainViewPointerPressed, AvaInteractivity.RoutingStrategies.Tunnel);
    }

    private void ScheduleEditorInitialization()
    {
        if (editorInitializationScheduled)
            return;

        editorInitializationScheduled = true;
        Dispatcher.UIThread.Post(() =>
        {
            editorInitializationScheduled = false;
            EnsureEditorCreated();
        }, DispatcherPriority.Background);
    }

    private void EnsureEditorCreated()
    {
        if (editor != null)
            return;

        SweetEditorControl createdEditor = new(controller)
        {
            HorizontalAlignment = HorizontalAlignment.Stretch,
            VerticalAlignment = VerticalAlignment.Stretch,
            Focusable = true,
        };
        if (DemoPlatformServices.Current?.IsAndroid == true)
            RenderOptions.SetTextRenderingMode(createdEditor, TextRenderingMode.Alias);

        createdEditor.AddHandler(InputElement.KeyDownEvent, OnEditorKeyDown, AvaInteractivity.RoutingStrategies.Tunnel);
        editor = createdEditor;
        editorHost.Children.Insert(0, createdEditor);
        InitializeDemo();
    }

    private void InitializeDemo()
    {
        if (demoInitialized)
            return;

        demoInitialized = true;
        controller.SetEditorIconProvider(iconProvider);
        controller.AddDecorationProvider(decorationProvider);
        controller.AddCompletionProvider(completionProvider);
        controller.AddNewLineActionProvider(newLineActionProvider);
        controller.SetInlineSuggestionListener(new DemoInlineSuggestionListener(UpdateStatus));
        controller.SetSelectionMenuHostManaged(true);
        controller.SetKeyMap(CreateEditorKeyMap());

        EditorSettings? settings = controller.GetSettings();
        if (settings != null)
        {
            bool isAndroid = DemoPlatformServices.Current?.IsAndroid == true;
            settings.SetTypeface("monospace");
            settings.SetEditorTextSize(isAndroid ? 14.0f : 13.25f);
            currentScale = GetDefaultScale();
            settings.SetScale(currentScale);
            settings.SetContentStartPadding(2);
            settings.SetFoldArrowMode(FoldArrowMode.AUTO);
            settings.SetCurrentLineRenderMode(CurrentLineRenderMode.BORDER);
            settings.SetGutterSticky(!isAndroid);
            settings.SetMaxGutterIcons(1);
            settings.SetWrapMode(wrapMode);
            settings.SetAutoIndentMode(AutoIndentMode.KEEP_INDENT);
            settings.SetBackspaceUnindent(true);
            settings.SetDecorationScrollRefreshMinIntervalMs(isAndroid ? 80 : 64);
            settings.SetDecorationOverscanViewportMultiplier(isAndroid ? 0.20f : 0.12f);
        }

        ApplyTheme();
        sampleLoader.LoadInitialSamples(typeof(MainView).Assembly);
        SyncSamplePickerSelection();
        RefreshActionState();
        UpdateFeatureStrip();
        if (sampleLoader.SampleFiles.Count > 0)
            UpdateStatus($"Loaded {sampleLoader.SampleFiles.Count} demo samples");
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private EditorKeyMap CreateEditorKeyMap()
    {
        EditorKeyMap keyMap = new(useVsCodeKeyMap ? KeyMap.Vscode().Bindings : KeyMap.DefaultKeyMap().Bindings);
        keyMap.RegisterCommand(
            new KeyBinding(new KeyChord(KeyModifier.CTRL, KeyCode.K), new KeyChord(KeyModifier.CTRL, KeyCode.D), 0),
            _ =>
            {
                controller.TriggerCompletion();
                UpdateStatus("Host keymap: completion triggered");
                return true;
            });
        return keyMap;
    }

    private void ApplyTheme()
    {
        ThemeVariant variant = darkTheme ? ThemeVariant.Dark : ThemeVariant.Light;
        Application.Current!.RequestedThemeVariant = variant;

        uint background = darkTheme ? 0xFF1B1E24 : 0xFFFAFBFD;
        uint surface = background;
        uint surfaceMuted = darkTheme ? 0xFF242A33 : 0xFFF1F4F8;
        uint border = darkTheme ? 0xFF313844 : 0xFFD7DEE8;
        uint foreground = darkTheme ? 0xFFD7DEE9 : 0xFF1F2937;
        uint secondary = darkTheme ? 0xFF7A8494 : 0xFF8A94A6;
        uint accent = darkTheme ? 0xFF4C9DFF : 0xFF0F7AD9;

        toolbarContainer.Background = CreateBrush(surface);
        toolbarContainer.BorderBrush = CreateBrush(border);
        Background = CreateBrush(background);
        statusBar.Background = CreateBrush(surface);
        statusBar.BorderBrush = CreateBrush(border);
        statusText.Foreground = CreateBrush(foreground);
        summaryText.Foreground = CreateBrush(secondary);
        samplePickerPopup.Background = CreateBrush(darkTheme ? 0xFF1B1E24u : 0xFFFFFFFFu);
        samplePickerPopup.BorderBrush = CreateBrush(darkTheme ? 0xFF313844u : 0xFFD7DEE8u);
        completionPopup.Background = CreateBrush(darkTheme ? 0xFF1B1E24u : 0xFFFFFFFFu);
        completionPopup.BorderBrush = CreateBrush(darkTheme ? 0xFF313844u : 0xFFD7DEE8u);
        selectionActionBar.Background = CreateBrush(darkTheme ? 0xFF1B1E24u : 0xFFFFFFFFu);
        selectionActionBar.BorderBrush = CreateBrush(darkTheme ? 0xFF313844u : 0xFFD7DEE8u);

        notificationPanel.DarkTheme = darkTheme;

        toolbarController.SamplePickerChrome.Background = CreateBrush(surfaceMuted);
        toolbarController.SamplePickerChrome.BorderBrush = CreateBrush(border);
        toolbarController.SamplePickerChrome.BorderThickness = new Thickness(1);
        toolbarController.SamplePickerLabel.Foreground = CreateBrush(foreground);
        toolbarController.SamplePickerChevron.Stroke = CreateBrush(foreground);
        toolbarController.SetTheme(darkTheme);
        toolbarController.SetWrapMode(wrapMode);
        ApplyToolbarChrome(foreground, surfaceMuted, border, accent);

        controller.ApplyTheme(CreateEditorTheme(darkTheme));
        if (samplePickerPopup.IsVisible)
        {
            RebuildSamplePickerItems();
            ScheduleChromeRefresh(DeferredChromeWork.SamplePickerPopup);
        }
        if (completionPopup.IsVisible)
        {
            RenderCompletionItems();
        }
        if (selectionActionBar.IsVisible)
        {
            RebuildSelectionActionBarItems(BuildSelectionActionBarItems());
        }
    }

    private static EditorTheme CreateEditorTheme(bool dark)
    {
        uint colorToken = dark ? 0xFF9CDCFEu : 0xFF0F766Eu;
        return (dark ? EditorTheme.Dark() : EditorTheme.Light())
            .DefineTextStyle((uint)DemoDecorationProvider.StyleColor, new TextStyle(unchecked((int)colorToken), 0));
    }

    private void PrepareForSampleLoad(DemoSampleFile sample)
    {
        activeSample = sample;
        currentLanguageId = sample.LanguageId;
        foldCollapsed = false;
        allowPassiveInlineSuggestion = false;
        CancelPendingInlineSuggestion();
        controller.DismissCompletion();
        controller.DismissInlineSuggestion();
        HideSamplePickerPopup();
        HideCompletionPopup();
        HideSelectionActionBar();
        controller.GetSettings()?.SetGutterSticky(DemoPlatformServices.Current?.IsAndroid != true);

        loadingIndicator.IsLoading = true;
        loadingIndicator.LoadingText = $"Loading {sample.FileName}...";

        UpdateFeatureStrip();
    }

    private void ApplyLanguageConfiguration(string languageId)
    {
        currentLanguageId = languageId;
        controller.SetLanguageConfiguration(languageId.Equals("lua", StringComparison.OrdinalIgnoreCase)
            ? new LanguageConfiguration(
                "lua",
                brackets: new List<BracketPair> { new("(", ")"), new("{", "}"), new("[", "]") },
                autoClosingPairs: new List<BracketPair>
                {
                    new("(", ")"),
                    new("{", "}"),
                    new("[", "]"),
                    new("\"", "\""),
                    new("'", "'")
                },
                lineComment: "--",
                tabSize: 4,
                insertSpaces: true)
            : new LanguageConfiguration(
                languageId,
                brackets: new List<BracketPair> { new("(", ")"), new("{", "}"), new("[", "]") },
                autoClosingPairs: new List<BracketPair>
                {
                    new("(", ")"),
                    new("{", "}"),
                    new("[", "]"),
                    new("\"", "\""),
                    new("'", "'")
                },
                lineComment: "//",
                blockComment: new BlockComment("/*", "*/"),
                tabSize: 4,
                insertSpaces: true));

        UpdateFeatureStrip();
    }

    private void ToggleTheme()
    {
        darkTheme = !darkTheme;
        HideCompletionPopup();
        ApplyTheme();
        controller.RequestDecorationRefresh();
        UpdateFeatureStrip();
        UpdateStatus(darkTheme ? "Theme: dark" : "Theme: light");
    }

    private void CycleWrapMode()
    {
        WrapMode[] modes = Enum.GetValues<WrapMode>();
        int index = Array.IndexOf(modes, wrapMode);
        wrapMode = modes[(index + 1) % modes.Length];
        controller.GetSettings()?.SetWrapMode(wrapMode);
        toolbarController.SetWrapMode(wrapMode);
        UpdateFeatureStrip();
        UpdateStatus($"Wrap: {wrapMode}");
    }

    private void StepScale(int delta)
    {
        EditorSettings? settings = controller.GetSettings();
        if (settings == null)
            return;

        int nearestIndex = 0;
        float bestDistance = float.MaxValue;
        for (int i = 0; i < ScalePresets.Length; i++)
        {
            float distance = Math.Abs(ScalePresets[i] - currentScale);
            if (distance < bestDistance)
            {
                bestDistance = distance;
                nearestIndex = i;
            }
        }

        int nextIndex = Math.Clamp(nearestIndex + delta, 0, ScalePresets.Length - 1);
        float nextScale = ScalePresets[nextIndex];
        currentScale = nextScale;
        settings.SetScale(nextScale);
        RefreshActionState();
        UpdateStatus($"Scale: {nextScale * 100:F0}%");
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private float GetDefaultScale() => DemoPlatformServices.Current?.IsAndroid == true ? 0.90f : 0.96f;

    private void TogglePerfOverlay()
    {
        perfOverlayEnabled = !perfOverlayEnabled;
        controller.SetPerfOverlayEnabled(perfOverlayEnabled);
        UpdateFeatureStrip();
        UpdateStatus(perfOverlayEnabled ? "Perf overlay: ON" : "Perf overlay: OFF");
    }

    private void ToggleKeyMap()
    {
        useVsCodeKeyMap = !useVsCodeKeyMap;
        controller.SetKeyMap(CreateEditorKeyMap());
        UpdateFeatureStrip();
        UpdateStatus(useVsCodeKeyMap ? "Keymap: VS Code" : "Keymap: default");
    }

    private void TriggerCompletion()
    {
        CancelPendingInlineSuggestion();
        controller.TriggerCompletion();
        UpdateFeatureStrip();
        UpdateStatus("Completion requested");
    }

    private void ShowInlineSuggestionAtCursor()
    {
        CancelPendingInlineSuggestion();
        TextPosition cursor = controller.GetCursorPosition();
        controller.ShowInlineSuggestion(new InlineSuggestion(cursor.Line, cursor.Column, InlineSuggestionText));
        ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar);
        UpdateStatus($"Ghost text shown at {cursor.Line}:{cursor.Column}");
    }

    private void InsertSnippetAtCursor()
    {
        controller.InsertSnippet(LinkedSnippet);
        UpdateStatus("Snippet inserted; use Tab to walk linked edits");
    }

    private void FoldAll()
    {
        controller.FoldAll();
        foldCollapsed = true;
        UpdateFeatureStrip();
        UpdateStatus("Folded all visible regions");
    }

    private void UnfoldAll()
    {
        controller.UnfoldAll();
        foldCollapsed = false;
        UpdateFeatureStrip();
        UpdateStatus("Unfolded all regions");
    }

    private void LoadLargeSample()
    {
        DemoSampleFile? large = sampleLoader.SampleFiles.FirstOrDefault(file =>
            file.FileName.EndsWith("large-demo.cpp", StringComparison.OrdinalIgnoreCase));
        if (large == null)
        {
            UpdateStatus("Large sample unavailable");
            return;
        }

        _ = sampleLoader.LoadSampleAsync(large);
    }

    private void SyncSamplePickerSelection()
    {
        string? selectedFileName = toolbarController.FileCombo.SelectedItem as string
            ?? activeSample?.FileName
            ?? sampleLoader.SampleFiles.FirstOrDefault()?.FileName;
        toolbarController.SetSamplePickerLabel(selectedFileName);
        RebuildSamplePickerItems();
        ScheduleChromeRefresh(DeferredChromeWork.SamplePickerPopup | DeferredChromeWork.Summary);
    }

    private void ToggleSamplePickerPopup()
    {
        if (samplePickerPopup.IsVisible)
        {
            HideSamplePickerPopup();
            return;
        }

        ShowSamplePickerPopup();
    }

    private void ShowSamplePickerPopup()
    {
        if (sampleLoader.SampleFiles.Count == 0 || !toolbarController.SamplePickerButton.IsEnabled)
            return;

        RebuildSamplePickerItems();
        samplePickerPopup.IsVisible = true;
        toolbarController.SetSamplePickerExpanded(true);
        ScheduleChromeRefresh(DeferredChromeWork.SamplePickerPopup);
    }

    private void HideSamplePickerPopup()
    {
        samplePickerPopup.IsVisible = false;
        toolbarController.SetSamplePickerExpanded(false);
    }

    private void RebuildSamplePickerItems()
    {
        samplePickerItemsPanel.Children.Clear();
        string? selectedFileName = toolbarController.FileCombo.SelectedItem as string ?? activeSample?.FileName;
        foreach (DemoSampleFile sample in sampleLoader.SampleFiles)
        {
            bool isSelected = string.Equals(sample.FileName, selectedFileName, StringComparison.Ordinal);
            samplePickerItemsPanel.Children.Add(BuildSamplePickerItem(sample, isSelected));
        }
    }

    private Control BuildSamplePickerItem(DemoSampleFile sample, bool isSelected)
    {
        uint foreground = darkTheme ? 0xFFD7DEE9u : 0xFF1F2937u;
        uint secondary = darkTheme ? 0xFF7A8494u : 0xFF8A94A6u;
        uint background = isSelected
            ? (darkTheme ? 0xFF2A3A52u : 0xFFE4F0FFu)
            : (darkTheme ? 0xFF1B1E24u : 0xFFFFFFFFu);
        uint border = isSelected
            ? (darkTheme ? 0xFF4C9DFFu : 0xFF0F7AD9u)
            : (darkTheme ? 0xFF313844u : 0xFFD7DEE8u);
        string detail = sample.IsGenerated ? "generated" : sample.LanguageId;

        Grid row = new()
        {
            ColumnDefinitions = new ColumnDefinitions("*,Auto"),
            ColumnSpacing = 8,
            HorizontalAlignment = HorizontalAlignment.Stretch,
            VerticalAlignment = VerticalAlignment.Center,
        };
        row.Children.Add(new TextBlock
        {
            Text = sample.FileName,
            FontSize = 12.5,
            FontWeight = isSelected ? FontWeight.SemiBold : FontWeight.Medium,
            Foreground = CreateBrush(foreground),
            TextTrimming = TextTrimming.CharacterEllipsis,
            VerticalAlignment = VerticalAlignment.Center,
        });

        TextBlock detailText = new()
        {
            Text = detail,
            FontSize = 10.5,
            Foreground = CreateBrush(secondary),
            VerticalAlignment = VerticalAlignment.Center,
            TextAlignment = TextAlignment.Right,
        };
        Grid.SetColumn(detailText, 1);
        row.Children.Add(detailText);

        Border chrome = new()
        {
            Padding = new Thickness(10, 8),
            CornerRadius = new CornerRadius(10),
            Background = CreateBrush(background),
            BorderBrush = CreateBrush(border),
            BorderThickness = new Thickness(1),
            Child = row,
        };

        Button button = new()
        {
            Background = Brushes.Transparent,
            BorderBrush = Brushes.Transparent,
            BorderThickness = new Thickness(0),
            Padding = new Thickness(0),
            HorizontalAlignment = HorizontalAlignment.Stretch,
            HorizontalContentAlignment = HorizontalAlignment.Stretch,
            Content = chrome,
        };
        button.Click += (_, _) =>
        {
            HideSamplePickerPopup();
            if (!string.Equals(toolbarController.FileCombo.SelectedItem as string, sample.FileName, StringComparison.Ordinal))
                toolbarController.FileCombo.SelectedItem = sample.FileName;
        };
        return button;
    }

    private void RepositionSamplePickerPopup()
    {
        if (!samplePickerPopup.IsVisible)
            return;

        if (!TryGetControlBoundsInLayoutRoot(toolbarController.SamplePickerButton, out Rect buttonBounds))
            return;

        double margin = 8;
        double rootWidth = layoutRoot.Bounds.Width;
        double rootHeight = layoutRoot.Bounds.Height;
        if (rootWidth <= 0 || rootHeight <= 0)
            return;

        double maxWidth = Math.Max(160, rootWidth - margin * 2);
        double width = Math.Clamp(Math.Max(buttonBounds.Width, 220), 160, maxWidth);
        samplePickerPopup.Width = width;
        samplePickerPopup.MaxHeight = Math.Max(120, Math.Min(SamplePickerPopupMaxHeight, rootHeight - buttonBounds.Bottom - margin * 2));
        samplePickerPopup.Measure(new Size(width, double.PositiveInfinity));

        double x = Math.Clamp(buttonBounds.X, margin, Math.Max(margin, rootWidth - width - margin));
        double y = Math.Max(margin, buttonBounds.Bottom + 4);
        samplePickerPopup.Margin = new Thickness(x, y, 0, 0);
    }

    private bool TryGetControlBoundsInLayoutRoot(Control control, out Rect bounds)
    {
        bounds = default;
        Point? origin = control.TranslatePoint(default, layoutRoot);
        if (!origin.HasValue)
            return false;

        bounds = new Rect(origin.Value, control.Bounds.Size);
        return bounds.Width > 0 && bounds.Height > 0;
    }

    private void OnMainViewPointerPressed(object? sender, PointerPressedEventArgs e)
    {
        if (!samplePickerPopup.IsVisible)
            return;

        Point point = e.GetPosition(layoutRoot);
        bool insideButton = TryGetControlBoundsInLayoutRoot(toolbarController.SamplePickerButton, out Rect buttonBounds) &&
                            buttonBounds.Contains(point);
        bool insidePopup = TryGetControlBoundsInLayoutRoot(samplePickerPopup, out Rect popupBounds) &&
                           popupBounds.Contains(point);
        if (!insideButton && !insidePopup)
            HideSamplePickerPopup();
    }

    private void MaybeShowInlineSuggestion(TextPosition cursor)
    {
        CancelPendingInlineSuggestion();
        if (!allowPassiveInlineSuggestion || !inlineSuggestionAutoEnabled || controller.IsInlineSuggestionShowing() || completionPopup.IsVisible)
            return;

        (bool hasSelection, _) = controller.GetSelection();
        if (hasSelection)
            return;

        Document? doc = controller.GetDocument();
        if (doc == null)
            return;

        string lineText = doc.GetLineText(cursor.Line) ?? string.Empty;
        if (lineText.Trim().Length == 0 || cursor.Column != lineText.Length)
            return;

        int token = ++pendingInlineSuggestionToken;
        DispatcherTimer.RunOnce(() =>
        {
            if (token != pendingInlineSuggestionToken || controller.IsInlineSuggestionShowing() || completionPopup.IsVisible)
                return;

            controller.ShowInlineSuggestion(new InlineSuggestion(cursor.Line, cursor.Column, InlineSuggestionText));
            UpdateSelectionActionBar();
        }, TimeSpan.FromMilliseconds(DemoPlatformServices.Current?.IsAndroid == true ? 1000 : 700));
    }

    private void ApplyToolbarChrome(uint foreground, uint surfaceMuted, uint border, uint accent)
    {
        foreach (Button button in toolbarController.ActionButtons)
        {
            button.Foreground = CreateBrush(foreground);
            button.Background = Brushes.Transparent;
            button.BorderBrush = Brushes.Transparent;

            if (button.Content is Border chrome)
            {
                bool active = ReferenceEquals(button, toolbarController.PerfButton) && perfOverlayEnabled;
                ApplyActionChrome(chrome, foreground, surfaceMuted, border, active ? accent : surfaceMuted, active ? 0xFFFFFFFFu : foreground);
            }
        }
    }

    private static void ApplyActionChrome(Border chrome, uint foreground, uint surfaceMuted, uint border, uint background, uint textColor)
    {
        chrome.Background = CreateBrush(background);
        chrome.BorderBrush = CreateBrush(border);
        chrome.BorderThickness = new Thickness(1);

        if (chrome.Child is AvaPath path)
        {
            path.Fill = CreateBrush(textColor);
            return;
        }

        if (chrome.Child is TextBlock label)
        {
            label.Foreground = CreateBrush(textColor);
            return;
        }

        if (chrome.Child is Grid grid)
        {
            foreach (Control child in grid.Children.OfType<Control>())
            {
                if (child is AvaPath iconPath)
                {
                    iconPath.Fill = CreateBrush(textColor);
                }
                else if (child is Border badge && badge.Child is TextBlock badgeText)
                {
                    badge.Background = CreateBrush(textColor);
                    badgeText.Foreground = CreateBrush(surfaceMuted);
                }
            }
        }
    }

    private void RefreshActionState()
    {
        bool canUndo = controller.CanUndo();
        bool canRedo = controller.CanRedo();
        toolbarController.UndoButton.IsEnabled = canUndo;
        toolbarController.UndoButton.Opacity = canUndo ? 1.0 : 0.42;
        toolbarController.RedoButton.IsEnabled = canRedo;
        toolbarController.RedoButton.Opacity = canRedo ? 1.0 : 0.42;

        float minScale = ScalePresets[0];
        float maxScale = ScalePresets[^1];
        bool canZoomOut = currentScale > minScale + 0.0001f;
        bool canZoomIn = currentScale < maxScale - 0.0001f;
        toolbarController.ZoomOutButton.IsEnabled = canZoomOut;
        toolbarController.ZoomOutButton.Opacity = canZoomOut ? 1.0 : 0.42;
        toolbarController.ZoomInButton.IsEnabled = canZoomIn;
        toolbarController.ZoomInButton.Opacity = canZoomIn ? 1.0 : 0.42;
    }

    private void ExecuteAction(bool succeeded, string success, string failed)
    {
        RefreshActionState();
        UpdateStatus(succeeded ? success : failed);
    }

    private void HandleSelectionMenuAction(string itemId)
    {
        switch (itemId)
        {
            case DemoSelectionMenuItemProvider.ActionDeleteSelection:
                if (!controller.GetSelection().hasSelection)
                {
                    UpdateStatus("Delete unavailable");
                    break;
                }

                (bool hasSelection, TextRange range) = controller.GetSelection();
                if (hasSelection)
                {
                    controller.DeleteText(range);
                    UpdateStatus("Selection deleted");
                }
                break;
            case DemoSelectionMenuItemProvider.ActionTriggerCompletion:
                TriggerCompletion();
                break;
            case DemoSelectionMenuItemProvider.ActionAcceptInlineSuggestion:
                controller.AcceptInlineSuggestion();
                UpdateStatus("Ghost accepted");
                break;
            case DemoSelectionMenuItemProvider.ActionDismissInlineSuggestion:
                controller.DismissInlineSuggestion();
                UpdateStatus("Ghost dismissed");
                break;
            case DemoSelectionMenuItemProvider.ActionShowInlineSuggestion:
                ShowInlineSuggestionAtCursor();
                break;
            case DemoSelectionMenuItemProvider.ActionToggleInlineSuggestionAuto:
                inlineSuggestionAutoEnabled = !inlineSuggestionAutoEnabled;
                UpdateFeatureStrip();
                UpdateStatus(inlineSuggestionAutoEnabled ? "Auto ghost: ON" : "Auto ghost: OFF");
                break;
            case DemoSelectionMenuItemProvider.ActionInsertSnippet:
                InsertSnippetAtCursor();
                break;
            case DemoSelectionMenuItemProvider.ActionFoldAll:
                FoldAll();
                break;
            case DemoSelectionMenuItemProvider.ActionUnfoldAll:
                UnfoldAll();
                break;
            case DemoSelectionMenuItemProvider.ActionLoadLargeSample:
                LoadLargeSample();
                break;
            case DemoSelectionMenuItemProvider.ActionTogglePerfOverlay:
                TogglePerfOverlay();
                break;
            case DemoSelectionMenuItemProvider.ActionToggleKeyMap:
                ToggleKeyMap();
                break;
        }

        Dispatcher.UIThread.Post(() => ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar), DispatcherPriority.Background);
    }

    private void ShowCompletionItems(IReadOnlyList<CompletionItem> items)
    {
        CancelPendingInlineSuggestion();
        currentCompletionItems.Clear();
        currentCompletionItems.AddRange(items);
        selectedCompletionIndex = currentCompletionItems.Count > 0 ? 0 : -1;
        RenderCompletionItems();
        completionPopup.IsVisible = currentCompletionItems.Count > 0;
        ScheduleChromeRefresh(DeferredChromeWork.CompletionPopup | DeferredChromeWork.Summary);
    }

    private void HideCompletionPopup()
    {
        completionPopup.IsVisible = false;
        selectedCompletionIndex = -1;
        currentCompletionItems.Clear();
        completionItemsPanel.Children.Clear();
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private void UpdateSelectionActionBar()
    {
        bool hasSelection = controller.GetSelection().hasSelection;
        bool inlineShowing = controller.IsInlineSuggestionShowing();
        bool hasTransientSelectionAnchor = !hasSelection && !inlineShowing && TryGetSelectionActionAnchor(out SelectionActionAnchorSnapshot snapshot) && snapshot.HasSelection;
        if (!hasSelection && !inlineShowing && !hasTransientSelectionAnchor)
        {
            HideSelectionActionBar();
            LogSelectionActionBarState("hide");
            return;
        }

        IReadOnlyList<SelectionMenuItem> items = BuildSelectionActionBarItems();
        if (items.Count == 0)
        {
            HideSelectionActionBar();
            LogSelectionActionBarState("empty");
            return;
        }

        RebuildSelectionActionBarItems(items);
        selectionActionBar.IsVisible = true;
        RepositionSelectionActionBar();
        LogSelectionActionBarState(hasSelection ? "selection" : inlineShowing ? "ghost" : "anchor");
    }

    private void RefreshSelectionActionBarWithStabilization(bool forceRetry = false)
    {
        ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar);
        if (!forceRetry && !IsImeVisibleInEditorHost())
        {
            pendingSelectionActionBarRefreshToken++;
            return;
        }

        ScheduleSelectionActionBarRefreshRetry();
    }

    private void ScheduleSelectionActionBarRefreshRetry()
    {
        int token = ++pendingSelectionActionBarRefreshToken;
        ScheduleSelectionActionBarRefreshRetry(token, 80);
        ScheduleSelectionActionBarRefreshRetry(token, 180);
        ScheduleSelectionActionBarRefreshRetry(token, 320);
        ScheduleSelectionActionBarRefreshRetry(token, 520);
        ScheduleSelectionActionBarRefreshRetry(token, 860);
        ScheduleSelectionActionBarRefreshRetry(token, 1160);
        ScheduleSelectionActionBarRefreshRetry(token, 1480);
    }

    private void ScheduleSelectionActionBarRefreshRetry(int token, int delayMs)
    {
        DispatcherTimer.RunOnce(() =>
        {
            if (token != pendingSelectionActionBarRefreshToken)
            {
                return;
            }

            ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar);
        }, TimeSpan.FromMilliseconds(delayMs));
    }

    private void HideSelectionActionBar()
    {
        selectionActionBar.IsVisible = false;
        selectionActionItemsPanel.Children.Clear();
        selectionActionBarItemsSignature = null;
    }

    private void RebuildSelectionActionBarItems(IReadOnlyList<SelectionMenuItem> items)
    {
        string signature = BuildSelectionActionBarSignature(items);
        if (signature == selectionActionBarItemsSignature && selectionActionItemsPanel.Children.Count == items.Count)
            return;

        selectionActionBarItemsSignature = signature;
        selectionActionItemsPanel.Children.Clear();
        foreach (SelectionMenuItem item in items)
        {
            selectionActionItemsPanel.Children.Add(BuildSelectionActionButton(item));
        }
    }

    private string BuildSelectionActionBarSignature(IReadOnlyList<SelectionMenuItem> items)
    {
        return $"{(darkTheme ? 'D' : 'L')}|{string.Join(";", items.Select(item => $"{item.Id}:{item.Label}:{(item.Enabled ? '1' : '0')}"))}";
    }

    private IReadOnlyList<SelectionMenuItem> BuildSelectionActionBarItems()
    {
        bool hasSelection = controller.GetSelection().hasSelection;
        List<SelectionMenuItem> merged = new()
        {
            new(SelectionMenuItem.ACTION_CUT, "Cut", hasSelection),
            new(SelectionMenuItem.ACTION_COPY, "Copy", hasSelection),
            new(SelectionMenuItem.ACTION_PASTE, "Paste"),
            new(SelectionMenuItem.ACTION_SELECT_ALL, "Select All"),
        };

        if (editor == null)
            return merged;

        foreach (SelectionMenuItem item in selectionMenuProvider.ProvideMenuItems(editor))
        {
            if (string.IsNullOrWhiteSpace(item.Id))
            {
                continue;
            }

            int existingIndex = merged.FindIndex(existing => string.Equals(existing.Id, item.Id, StringComparison.Ordinal));
            if (existingIndex >= 0)
            {
                merged[existingIndex] = item;
            }
            else
            {
                merged.Add(item);
            }
        }

        if (hasSelection && merged.All(item => !string.Equals(item.Id, DemoSelectionMenuItemProvider.ActionDeleteSelection, StringComparison.Ordinal)))
        {
            merged.Add(new SelectionMenuItem(DemoSelectionMenuItemProvider.ActionDeleteSelection, "Delete", true));
        }

        return merged;
    }

    private Control BuildSelectionActionButton(SelectionMenuItem item)
    {
        Border chrome = new()
        {
            CornerRadius = new CornerRadius(999),
            Padding = new Thickness(10, 5),
            Background = CreateBrush(darkTheme ? 0xFF242A33u : 0xFFF1F4F8u),
            BorderBrush = CreateBrush(darkTheme ? 0xFF313844u : 0xFFD7DEE8u),
            BorderThickness = new Thickness(1),
            Child = new TextBlock
            {
                Text = item.Label,
                FontSize = 11.5,
                FontWeight = FontWeight.SemiBold,
                Foreground = CreateBrush(item.Enabled
                    ? (darkTheme ? 0xFFD7DEE9u : 0xFF1F2937u)
                    : (darkTheme ? 0xFF6B7380u : 0xFF98A1B2u)),
                VerticalAlignment = VerticalAlignment.Center,
                TextAlignment = TextAlignment.Center,
            },
        };

        Button button = new()
        {
            Background = Brushes.Transparent,
            BorderBrush = Brushes.Transparent,
            BorderThickness = new Thickness(0),
            Padding = new Thickness(0),
            Content = chrome,
            IsEnabled = item.Enabled,
        };
        button.Click += (_, _) => HandleSelectionActionBarItem(item.Id);
        return button;
    }

    private void HandleSelectionActionBarItem(string itemId)
    {
        switch (itemId)
        {
            case SelectionMenuItem.ACTION_CUT:
                if (!controller.GetSelection().hasSelection)
                {
                    UpdateStatus("Cut unavailable");
                    break;
                }
                controller.CutToClipboard();
                UpdateStatus("Cut");
                break;
            case SelectionMenuItem.ACTION_COPY:
                if (!controller.GetSelection().hasSelection)
                {
                    UpdateStatus("Copy unavailable");
                    break;
                }
                controller.CopyToClipboard();
                UpdateStatus("Copied");
                break;
            case SelectionMenuItem.ACTION_PASTE:
                controller.PasteFromClipboard();
                UpdateStatus("Pasted");
                break;
            case SelectionMenuItem.ACTION_SELECT_ALL:
                controller.SelectAll();
                UpdateStatus("Select all");
                break;
            default:
                HandleSelectionMenuAction(itemId);
                return;
        }

        Dispatcher.UIThread.Post(() => ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar), DispatcherPriority.Background);
    }

    private void RepositionSelectionActionBar()
    {
        if (!selectionActionBar.IsVisible)
        {
            return;
        }

        double hostWidth = editorHost.Bounds.Width;
        double hostHeight = editorHost.Bounds.Height;
        if (hostWidth <= 0 || hostHeight <= 0)
        {
            return;
        }

        double margin = 6;
        double maxWidth = Math.Max(120, hostWidth - margin * 2);
        double minWidth = Math.Min(SelectionActionBarMinWidth, maxWidth);
        selectionActionScrollViewer.MaxWidth = Math.Max(108, maxWidth - 12);
        selectionActionBar.MaxWidth = maxWidth;
        selectionActionBar.Measure(new Size(maxWidth, double.PositiveInfinity));
        Size desiredSize = selectionActionBar.DesiredSize;
        double menuWidth = Math.Clamp(desiredSize.Width, minWidth, maxWidth);
        double menuHeight = Math.Max(36, desiredSize.Height);
        double safeBottom = hostHeight - margin;
        if (DemoPlatformServices.Current?.TryGetImeTopInEditorHostDip(this, editorHost, out double imeTopInHostDip) == true)
        {
            safeBottom = Math.Min(safeBottom, imeTopInHostDip - margin);
        }

        double x;
        double y;
        if (TryGetSelectionActionAnchor(out SelectionActionAnchorSnapshot anchor) && anchor.HasSelection)
        {
            CursorRect start = anchor.StartRect;
            CursorRect end = anchor.EndRect;
            CursorRect cursorRect = anchor.CursorRect.Height > 0 ? anchor.CursorRect : controller.GetCursorRect();
            bool hasSelectionRects = start.Height > 0 && end.Height > 0;
            double lineHeight = Math.Max(1, Math.Max(cursorRect.Height, Math.Max(start.Height, end.Height)));
            double startBottom = start.Y + Math.Max(1, start.Height);
            double endBottom = end.Y + Math.Max(1, end.Height);
            double selectionTop = hasSelectionRects ? Math.Min(start.Y, end.Y) : cursorRect.Y;
            double selectionBottom = hasSelectionRects
                ? Math.Max(startBottom, endBottom)
                : cursorRect.Y + Math.Max(1, cursorRect.Height);
            double anchorXCenter = anchor.HasAnchorPoint
                ? anchor.AnchorPoint.X
                : hasSelectionRects
                    ? (start.X + end.X) * 0.5
                    : cursorRect.X;
            double above;
            double below;
            if (anchor.HasAnchorPoint)
            {
                above = anchor.AnchorPoint.Y - menuHeight - SelectionActionBarVerticalOffset;
                below = anchor.AnchorPoint.Y + lineHeight + SelectionActionBarVerticalOffset;
            }
            else
            {
                above = selectionTop - menuHeight - SelectionActionBarVerticalOffset;
                below = selectionBottom + SelectionActionBarVerticalOffset;
            }
            bool canPlaceAbove = above >= margin;
            bool canPlaceBelow = (below + menuHeight) <= safeBottom;
            x = anchorXCenter - menuWidth * 0.5;
            if (canPlaceAbove)
            {
                y = above;
            }
            else if (canPlaceBelow)
            {
                y = below;
            }
            else
            {
                double spaceAbove = Math.Max(0, selectionTop - margin);
                double spaceBelow = Math.Max(0, safeBottom - selectionBottom);
                y = spaceAbove >= spaceBelow
                    ? Math.Max(margin, Math.Min(above, safeBottom - menuHeight))
                    : Math.Clamp(below, margin, Math.Max(margin, safeBottom - menuHeight));
            }
        }
        else
        {
            CursorRect cursor = anchor.CursorRect.Height > 0 ? anchor.CursorRect : controller.GetCursorRect();
            double anchorX = anchor.HasAnchorPoint ? anchor.AnchorPoint.X : cursor.X;
            double anchorY = anchor.HasAnchorPoint ? anchor.AnchorPoint.Y : cursor.Y;
            double above = anchorY - menuHeight - SelectionActionBarVerticalOffset;
            double below = anchorY + Math.Max(1, cursor.Height) + SelectionActionBarVerticalOffset;
            x = anchorX - menuWidth * 0.5;
            y = above >= margin ? above : below;
        }

        x = Math.Clamp(x, margin, Math.Max(margin, hostWidth - menuWidth - margin));
        y = Math.Clamp(y, margin, Math.Max(margin, safeBottom - menuHeight));
        selectionActionBar.Margin = new Thickness(x, y, 0, 0);
    }

    private bool IsImeVisibleInEditorHost()
    {
        return DemoPlatformServices.Current?.TryGetImeTopInEditorHostDip(this, editorHost, out double imeTopInHostDip) == true &&
               imeTopInHostDip < editorHost.Bounds.Height - 1;
    }

    private void CaptureSelectionActionAnchor(TextRange? range)
    {
        CaptureSelectionActionAnchor(range, null);
    }

    private void CaptureSelectionActionAnchor(TextRange? range, TextPosition? cursorOverride)
    {
        CaptureSelectionActionAnchor(range, cursorOverride, null);
    }

    private void CaptureSelectionActionAnchor(TextRange? range, TextPosition? cursorOverride, PointF? gesturePoint)
    {
        Point? anchorPoint = ToAnchorPoint(gesturePoint);
        if (!anchorPoint.HasValue &&
            range is TextRange carriedSelection &&
            TryGetCarriedSelectionAnchorPoint(carriedSelection, out Point preservedAnchorPoint))
        {
            anchorPoint = preservedAnchorPoint;
        }

        if (range is TextRange &&
            !anchorPoint.HasValue &&
            ShouldPreferGestureOnlySelectionAnchor() &&
            TryCreateCursorActionAnchorSnapshot(cursorOverride, null, out SelectionActionAnchorSnapshot deferredCursorSnapshot))
        {
            recentSelectionActionAnchor = deferredCursorSnapshot;
            recentSelectionActionAnchorTickMs = Environment.TickCount64;
            return;
        }

        if (range is TextRange selection && TryCreateSelectionActionAnchorSnapshot(selection, anchorPoint, out SelectionActionAnchorSnapshot selectionSnapshot))
        {
            recentSelectionActionAnchor = selectionSnapshot;
            recentSelectionActionAnchorTickMs = Environment.TickCount64;
            return;
        }

        if (TryCreateCursorActionAnchorSnapshot(cursorOverride, anchorPoint, out SelectionActionAnchorSnapshot cursorSnapshot))
        {
            recentSelectionActionAnchor = cursorSnapshot;
            recentSelectionActionAnchorTickMs = Environment.TickCount64;
            return;
        }

        if (range is not TextRange)
        {
            if (!IsImeVisibleInEditorHost())
                recentSelectionActionAnchor = null;
        }
    }

    private bool TryGetSelectionActionAnchor(out SelectionActionAnchorSnapshot anchor)
    {
        (bool hasSelection, TextRange selectionRange) = controller.GetSelection();
        Point? cachedSelectionAnchorPoint = TryResolveSelectionAnchorPoint(selectionRange);
        if (hasSelection && TryCreateSelectionActionAnchorSnapshot(selectionRange, cachedSelectionAnchorPoint, out SelectionActionAnchorSnapshot liveSelectionAnchor))
        {
            anchor = liveSelectionAnchor;
            recentSelectionActionAnchor = anchor;
            recentSelectionActionAnchorTickMs = Environment.TickCount64;
            return true;
        }

        Point? cachedCursorAnchorPoint = recentSelectionActionAnchor is SelectionActionAnchorSnapshot cachedCursor &&
                                         cachedCursor.HasAnchorPoint
            ? cachedCursor.AnchorPoint
            : null;
        if (controller.IsInlineSuggestionShowing() && TryCreateCursorActionAnchorSnapshot(null, cachedCursorAnchorPoint, out SelectionActionAnchorSnapshot liveCursorAnchor))
        {
            anchor = liveCursorAnchor;
            recentSelectionActionAnchor = anchor;
            recentSelectionActionAnchorTickMs = Environment.TickCount64;
            return true;
        }

        if (!IsImeVisibleInEditorHost() || recentSelectionActionAnchor is not SelectionActionAnchorSnapshot cached)
        {
            anchor = default;
            return false;
        }

        if ((Environment.TickCount64 - recentSelectionActionAnchorTickMs) > SelectionActionAnchorRetentionMs)
        {
            recentSelectionActionAnchor = null;
            anchor = default;
            return false;
        }

        anchor = cached;
        return true;
    }

    private bool IsRecentSelectionActionAnchorAvailable()
    {
        return recentSelectionActionAnchor is SelectionActionAnchorSnapshot anchor &&
               anchor.HasSelection &&
               (Environment.TickCount64 - recentSelectionActionAnchorTickMs) <= SelectionActionAnchorRetentionMs;
    }

    private bool TryCreateSelectionActionAnchorSnapshot(TextRange range, Point? anchorPoint, out SelectionActionAnchorSnapshot snapshot)
    {
        snapshot = default;
        Document? document = controller.GetDocument();
        if (document == null || !TrySanitizeSelectionRange(range, document, out TextRange sanitizedRange))
            return false;

        CursorRect startRect = default;
        CursorRect endRect = default;
        if (!(anchorPoint.HasValue && ShouldPreferGestureOnlySelectionAnchor()))
        {
            startRect = controller.GetPositionRect(sanitizedRange.Start.Line, sanitizedRange.Start.Column);
            endRect = controller.GetPositionRect(sanitizedRange.End.Line, sanitizedRange.End.Column);
        }

        snapshot = new SelectionActionAnchorSnapshot(
            sanitizedRange,
            startRect,
            endRect,
            controller.GetCursorRect(),
            anchorPoint ?? default,
            anchorPoint.HasValue,
            true);
        return true;
    }

    private bool TryCreateCursorActionAnchorSnapshot(TextPosition? cursorOverride, Point? anchorPoint, out SelectionActionAnchorSnapshot snapshot)
    {
        snapshot = default;
        CursorRect cursorRect = controller.GetCursorRect();
        if (cursorOverride.HasValue && controller.GetDocument() is Document document && TryClampPosition(cursorOverride.Value, document, Math.Max(0, document.GetLineCount()), out TextPosition clampedCursor))
        {
            cursorRect = controller.GetPositionRect(clampedCursor.Line, clampedCursor.Column);
        }

        if (cursorRect.Height <= 0)
            return false;

        snapshot = new SelectionActionAnchorSnapshot(
            default,
            default,
            default,
            cursorRect,
            anchorPoint ?? default,
            anchorPoint.HasValue,
            false);
        return true;
    }

    private static Point? ToAnchorPoint(PointF? gesturePoint)
    {
        if (gesturePoint is not PointF point)
            return null;

        return new Point(point.X, point.Y);
    }

    private bool TryGetCarriedSelectionAnchorPoint(TextRange selection, out Point anchorPoint)
    {
        anchorPoint = default;
        Point? resolved = TryResolveSelectionAnchorPoint(selection);
        if (!resolved.HasValue)
            return false;

        anchorPoint = resolved.Value;
        return true;
    }

    private Point? TryResolveSelectionAnchorPoint(TextRange selection)
    {
        if (recentSelectionActionAnchor is not SelectionActionAnchorSnapshot cached ||
            !cached.HasSelection ||
            !cached.HasAnchorPoint)
        {
            return null;
        }

        if ((Environment.TickCount64 - recentSelectionActionAnchorTickMs) > SelectionActionAnchorRetentionMs)
            return null;

        Document? document = controller.GetDocument();
        if (document == null ||
            !TrySanitizeSelectionRange(selection, document, out TextRange sanitizedSelection) ||
            !TrySanitizeSelectionRange(cached.Range, document, out TextRange sanitizedCached))
        {
            return null;
        }

        return RangesOverlapOrTouch(sanitizedCached, sanitizedSelection)
            ? cached.AnchorPoint
            : null;
    }

    private bool ShouldPreferGestureOnlySelectionAnchor()
    {
        if (DemoPlatformServices.Current?.IsAndroid != true)
            return false;

        if (IsImeVisibleInEditorHost())
            return true;

        Document? document = controller.GetDocument();
        return Math.Max(0, document?.GetLineCount() ?? 0) >= 12000;
    }

    private bool ShouldDeferLargeDocumentUiRefresh()
    {
        if (DemoPlatformServices.Current?.IsAndroid != true)
            return false;

        Document? document = controller.GetDocument();
        return Math.Max(0, document?.GetLineCount() ?? 0) >= 12000;
    }

    private static bool TrySanitizeSelectionRange(TextRange range, Document document, out TextRange sanitized)
    {
        sanitized = default;
        int lineCount = Math.Max(0, document.GetLineCount());
        if (lineCount <= 0)
            return false;

        TextRange normalized = NormalizeRange(range);
        if (!TryClampPosition(normalized.Start, document, lineCount, out TextPosition start) ||
            !TryClampPosition(normalized.End, document, lineCount, out TextPosition end))
        {
            return false;
        }

        if (ComparePositions(start, end) >= 0)
            return false;

        sanitized = new TextRange { Start = start, End = end };
        return true;
    }

    private static bool RangesOverlapOrTouch(TextRange left, TextRange right)
    {
        TextRange normalizedLeft = NormalizeRange(left);
        TextRange normalizedRight = NormalizeRange(right);
        return ComparePositions(normalizedLeft.End, normalizedRight.Start) >= 0 &&
               ComparePositions(normalizedRight.End, normalizedLeft.Start) >= 0;
    }

    private static bool TryClampPosition(TextPosition position, Document document, int lineCount, out TextPosition clamped)
    {
        clamped = default;
        if (lineCount <= 0)
            return false;

        int line = Math.Clamp(position.Line, 0, lineCount - 1);
        string lineText = document.GetLineText(line) ?? string.Empty;
        int column = Math.Clamp(position.Column, 0, lineText.Length);
        clamped = new TextPosition { Line = line, Column = column };
        return true;
    }

    private void LogSelectionActionBarState(string reason)
    {
        if (DemoPlatformServices.Current?.IsAndroid != true)
            return;

        bool imeVisible = IsImeVisibleInEditorHost();
        bool hasSelection = controller.GetSelection().hasSelection;
        bool inlineShowing = controller.IsInlineSuggestionShowing();
        bool hasAnchor = !hasSelection && !inlineShowing && IsRecentSelectionActionAnchorAvailable();
        if (!imeVisible && !selectionActionBar.IsVisible && !hasAnchor)
            return;

        Console.Error.WriteLine(
            $"SelectionActionBar[{reason}]: visible={selectionActionBar.IsVisible} actual={hasSelection} inline={inlineShowing} anchor={hasAnchor} ime={imeVisible}");
    }

    private readonly record struct SelectionActionAnchorSnapshot(
        TextRange Range,
        CursorRect StartRect,
        CursorRect EndRect,
        CursorRect CursorRect,
        Point AnchorPoint,
        bool HasAnchorPoint,
        bool HasSelection);

    private void RepositionCompletionPopup()
    {
        if (!completionPopup.IsVisible)
            return;

        double hostWidth = editorHost.Bounds.Width;
        double hostHeight = editorHost.Bounds.Height;
        if (hostWidth <= 0 || hostHeight <= 0)
            return;

        CursorRect rect = controller.GetCursorRect();
        double margin = 6;
        double width = Math.Min(CompletionPopupWidth, Math.Max(CompletionPopupMinWidth, hostWidth - margin * 2));
        if (width > hostWidth - margin * 2)
            width = Math.Max(120, hostWidth - margin * 2);

        double cursorLeft = rect.X;
        double cursorTop = rect.Y;
        double cursorBottom = cursorTop + rect.Height;
        double safeBottom = hostHeight - margin;
        if (DemoPlatformServices.Current?.TryGetImeTopInEditorHostDip(this, editorHost, out double imeTopInHostDip) == true)
            safeBottom = Math.Min(safeBottom, imeTopInHostDip - margin);

        double popupHeight = Math.Min(
            CompletionRowHeight * Math.Min(Math.Max(currentCompletionItems.Count, 1), CompletionMaxVisibleItems) + 12,
            Math.Max(CompletionRowHeight + 12, safeBottom - margin));

        double x = Math.Clamp(cursorLeft, margin, Math.Max(margin, hostWidth - width - margin));
        double belowY = cursorBottom + 4;
        double aboveY = cursorTop - popupHeight - 4;
        double y;
        if (belowY + popupHeight <= safeBottom)
            y = belowY;
        else if (aboveY >= margin)
            y = aboveY;
        else
            y = Math.Clamp(belowY, margin, Math.Max(margin, safeBottom - popupHeight));

        completionPopup.Width = width;
        completionPopup.MaxHeight = popupHeight;
        completionPopup.Margin = new Thickness(x, y, 0, 0);
    }

    private void ApplyCompletionItem(CompletionItem item)
    {
        string text = item.InsertText ?? item.Label;
        if (item.TextEditValue != null)
        {
            controller.DeleteText(item.TextEditValue.Range);
            text = item.TextEditValue.NewText;
        }
        else if (TryGetSafeCompletionReplacementRange(out TextRange range))
        {
            controller.DeleteText(range);
        }

        if (item.InsertTextFormat == CompletionItem.INSERT_TEXT_FORMAT_SNIPPET)
            controller.InsertSnippet(text);
        else
            controller.InsertText(text);

        RefreshActionState();
        controller.DismissCompletion();
    }

    private void OnEditorKeyDown(object? sender, KeyEventArgs e)
    {
        if (samplePickerPopup.IsVisible && e.Key == Key.Escape)
        {
            HideSamplePickerPopup();
            e.Handled = true;
            return;
        }

        if (completionPopup.IsVisible && currentCompletionItems.Count > 0)
        {
            if (e.Key == Key.Down)
            {
                MoveCompletionSelection(1);
                e.Handled = true;
                return;
            }

            if (e.Key == Key.Up)
            {
                MoveCompletionSelection(-1);
                e.Handled = true;
                return;
            }

            if (e.Key == Key.Enter && TryGetSelectedCompletionItem(out CompletionItem? item))
            {
                ApplyCompletionItem(item!);
                UpdateStatus($"Completion applied: {item!.Label}");
                HideCompletionPopup();
                e.Handled = true;
                return;
            }
        }

        if (completionPopup.IsVisible && e.Key == Key.Escape)
        {
            HideCompletionPopup();
            controller.DismissCompletion();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F1)
        {
            TriggerCompletion();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F2)
        {
            ShowInlineSuggestionAtCursor();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F3)
        {
            InsertSnippetAtCursor();
            e.Handled = true;
        }
    }

    private void EnsureCursorVisibleForAndroid()
    {
        IDemoPlatformServices? platform = DemoPlatformServices.Current;
        if (platform?.IsAndroid != true)
            return;

        if (!platform.TryGetImeTopInEditorHostDip(this, editorHost, out double imeTopInHostDip))
            return;

        CursorRect rect = controller.GetCursorRect();
        ScrollMetrics scroll = controller.GetScrollMetrics();
        double safeTop = 8;
        double safeBottom = imeTopInHostDip - 12;
        double cursorTopInViewport = rect.Y;
        double cursorBottomInViewport = rect.Y + Math.Max(1, rect.Height);
        if (cursorBottomInViewport > safeBottom)
        {
            controller.SetScroll(scroll.ScrollX, scroll.ScrollY + (float)(cursorBottomInViewport - safeBottom));
        }
        else if (cursorTopInViewport < safeTop)
        {
            controller.SetScroll(scroll.ScrollX, Math.Max(0, scroll.ScrollY - (float)(safeTop - cursorTopInViewport)));
        }
    }

    private void UpdateFeatureStrip()
    {
        uint surfaceMuted = darkTheme ? 0xFF242A33u : 0xFFF1F4F8u;
        uint border = darkTheme ? 0xFF313844u : 0xFFD7DEE8u;
        uint foreground = darkTheme ? 0xFFD7DEE9u : 0xFF1F2937u;
        uint accent = darkTheme ? 0xFF4C9DFFu : 0xFF0F7AD9u;
        toolbarController.SetWrapMode(wrapMode);
        ApplyToolbarChrome(foreground, surfaceMuted, border, accent);
        if (selectionActionBar.IsVisible)
        {
            ScheduleChromeRefresh(DeferredChromeWork.SelectionActionBar);
        }
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private void CancelPendingInlineSuggestion()
    {
        pendingInlineSuggestionToken++;
    }

    private void UpdateSummary()
    {
        TextPosition cursor = controller.GetCursorPosition();
        string wrapLabel = wrapMode switch
        {
            WrapMode.WORD_BREAK => "W",
            WrapMode.CHAR_BREAK => "C",
            _ => "N",
        };
        string backendLabel = decorationProvider.HighlightBackendLabel.Contains("native", StringComparison.OrdinalIgnoreCase)
            ? "SweetLine"
            : decorationProvider.HighlightBackendLabel;
        string sampleName = activeSample == null ? "Sample" : System.IO.Path.GetFileNameWithoutExtension(activeSample.FileName);
        string completionLabel = completionPopup.IsVisible ? $" · C{currentCompletionItems.Count}" : string.Empty;
        string perfLabel = perfOverlayEnabled ? " · FPS" : string.Empty;
        string nextValue = $"{sampleName} · {currentLanguageId} · {backendLabel} · {wrapLabel} · {currentScale * 100:F0}% · {cursor.Line + 1}:{cursor.Column + 1}{completionLabel}{perfLabel}";
        if (string.Equals(lastSummaryValue, nextValue, StringComparison.Ordinal))
            return;

        lastSummaryValue = nextValue;
        summaryText.Text = nextValue;
    }

    private void ScheduleChromeRefresh(DeferredChromeWork work)
    {
        ScheduleChromeRefresh(work, DispatcherPriority.Background);
    }

    private void ScheduleChromeRefresh(DeferredChromeWork work, DispatcherPriority priority)
    {
        pendingChromeWork |= work;
        if (chromeRefreshScheduled)
            return;

        chromeRefreshScheduled = true;
        Dispatcher.UIThread.Post(ApplyScheduledChromeRefresh, priority);
    }

    private void ApplyScheduledChromeRefresh()
    {
        chromeRefreshScheduled = false;
        DeferredChromeWork work = pendingChromeWork;
        pendingChromeWork = DeferredChromeWork.None;

        if ((work & DeferredChromeWork.CursorVisibility) != 0)
            EnsureCursorVisibleForAndroid();

        if ((work & DeferredChromeWork.SamplePickerPopup) != 0 && samplePickerPopup.IsVisible)
            RepositionSamplePickerPopup();

        if ((work & DeferredChromeWork.CompletionPopup) != 0 && completionPopup.IsVisible)
            RepositionCompletionPopup();

        if ((work & DeferredChromeWork.SelectionActionBar) != 0)
            UpdateSelectionActionBar();

        if ((work & DeferredChromeWork.Summary) != 0)
            UpdateSummary();
    }

    private void UpdateStatus(string message)
    {
        Dispatcher.UIThread.Post(() =>
        {
            statusText.Text = message;
            loadingIndicator.IsLoading = false;
        });
    }

    private void RenderCompletionItems()
    {
        completionItemsPanel.Children.Clear();
        for (int i = 0; i < currentCompletionItems.Count; i++)
        {
            completionItemsPanel.Children.Add(BuildCompletionItemView(currentCompletionItems[i], i == selectedCompletionIndex, i));
        }
        EnsureSelectedCompletionVisible();
    }

    private Control BuildCompletionItemView(CompletionItem item, bool isSelected, int index)
    {
        string typeText = !string.IsNullOrWhiteSpace(item.Detail)
            ? item.Detail!
            : CompletionKindText(item.Kind);

        Border kindBadge = new()
        {
            Width = 18,
            Height = 18,
            CornerRadius = new CornerRadius(999),
            Background = CreateBrush(CompletionKindBadgeColor(item.Kind)),
            Child = new TextBlock
            {
                Text = CompletionKindLetter(item.Kind),
                FontSize = 10,
                FontWeight = FontWeight.Bold,
                Foreground = CreateBrush(0xFFFFFFFFu),
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center,
                TextAlignment = TextAlignment.Center,
            },
        };

        Grid row = new()
        {
            ColumnDefinitions = new ColumnDefinitions("Auto,*,Auto"),
            ColumnSpacing = 8,
            HorizontalAlignment = HorizontalAlignment.Stretch,
            VerticalAlignment = VerticalAlignment.Center,
        };

        row.Children.Add(kindBadge);

        TextBlock label = new()
        {
            Text = item.Label,
            FontSize = 13,
            FontWeight = FontWeight.Medium,
            TextTrimming = TextTrimming.CharacterEllipsis,
            Foreground = CreateBrush(darkTheme ? 0xFFD8DEE9u : 0xFF1F2937u),
            VerticalAlignment = VerticalAlignment.Center,
        };
        Grid.SetColumn(label, 1);
        row.Children.Add(label);

        TextBlock detail = new()
        {
            Text = typeText,
            FontSize = 11,
            TextTrimming = TextTrimming.CharacterEllipsis,
            Foreground = CreateBrush(darkTheme ? 0xFF7A8494u : 0xFF8A94A6u),
            VerticalAlignment = VerticalAlignment.Center,
            TextAlignment = TextAlignment.Right,
            HorizontalAlignment = HorizontalAlignment.Right,
            MaxWidth = 108,
        };
        Grid.SetColumn(detail, 2);
        row.Children.Add(detail);

        Border chrome = new()
        {
            Background = isSelected ? CreateBrush(darkTheme ? 0xFF2A313Cu : 0xFFEAF3FFu) : Brushes.Transparent,
            CornerRadius = new CornerRadius(6),
            MinHeight = CompletionRowHeight,
            Padding = new Thickness(8, 2),
            HorizontalAlignment = HorizontalAlignment.Stretch,
            Child = row,
        };

        Button button = new()
        {
            Background = Brushes.Transparent,
            BorderBrush = Brushes.Transparent,
            BorderThickness = new Thickness(0),
            Padding = new Thickness(0),
            HorizontalAlignment = HorizontalAlignment.Stretch,
            HorizontalContentAlignment = HorizontalAlignment.Stretch,
            Content = chrome,
        };
        button.Click += (_, _) =>
        {
            selectedCompletionIndex = index;
            RenderCompletionItems();
            ApplyCompletionItem(item);
            UpdateStatus($"Completion applied: {item.Label}");
            HideCompletionPopup();
        };
        return button;
    }

    private bool TryGetSafeCompletionReplacementRange(out TextRange range)
    {
        range = default;
        if (controller.GetWordRangeAtCursor() is not TextRange candidate)
            return false;

        Document? document = controller.GetDocument();
        if (document == null)
            return false;

        TextPosition cursor = controller.GetCursorPosition();
        TextRange normalized = NormalizeRange(candidate);
        if (normalized.Start.Line != cursor.Line || normalized.End.Line != cursor.Line)
            return false;

        string lineText = document.GetLineText(cursor.Line) ?? string.Empty;
        if (normalized.Start.Column < 0 || normalized.Start.Column >= normalized.End.Column || normalized.End.Column > lineText.Length)
            return false;

        int clampedCursor = Math.Clamp(cursor.Column, 0, lineText.Length);
        if (clampedCursor < normalized.Start.Column || clampedCursor > normalized.End.Column)
            return false;

        range = normalized;
        return true;
    }

    private static TextRange NormalizeRange(TextRange range)
    {
        return ComparePositions(range.Start, range.End) <= 0
            ? range
            : new TextRange { Start = range.End, End = range.Start };
    }

    private static int ComparePositions(TextPosition left, TextPosition right)
    {
        int lineCompare = left.Line.CompareTo(right.Line);
        return lineCompare != 0 ? lineCompare : left.Column.CompareTo(right.Column);
    }

    private void MoveCompletionSelection(int delta)
    {
        if (currentCompletionItems.Count == 0)
            return;

        selectedCompletionIndex = Math.Clamp(selectedCompletionIndex + delta, 0, currentCompletionItems.Count - 1);
        RenderCompletionItems();
    }

    private void EnsureSelectedCompletionVisible()
    {
        if (selectedCompletionIndex < 0)
            return;

        double itemTop = selectedCompletionIndex * CompletionRowHeight;
        double itemBottom = itemTop + CompletionRowHeight;
        double viewportTop = completionScrollViewer.Offset.Y;
        double viewportBottom = viewportTop + completionScrollViewer.Viewport.Height;
        if (itemTop < viewportTop)
        {
            completionScrollViewer.Offset = new Vector(0, itemTop);
        }
        else if (itemBottom > viewportBottom)
        {
            completionScrollViewer.Offset = new Vector(0, Math.Max(0, itemBottom - completionScrollViewer.Viewport.Height));
        }
    }

    private bool TryGetSelectedCompletionItem(out CompletionItem? item)
    {
        if (selectedCompletionIndex >= 0 && selectedCompletionIndex < currentCompletionItems.Count)
        {
            item = currentCompletionItems[selectedCompletionIndex];
            return true;
        }

        item = null;
        return false;
    }

    private static string CompletionKindLetter(int kind) => kind switch
    {
        CompletionItem.KIND_KEYWORD => "K",
        CompletionItem.KIND_FUNCTION => "F",
        CompletionItem.KIND_VARIABLE => "V",
        CompletionItem.KIND_CLASS => "C",
        CompletionItem.KIND_INTERFACE => "I",
        CompletionItem.KIND_MODULE => "M",
        CompletionItem.KIND_PROPERTY => "P",
        CompletionItem.KIND_SNIPPET => "S",
        _ => "T",
    };

    private static string CompletionKindText(int kind) => kind switch
    {
        CompletionItem.KIND_KEYWORD => "keyword",
        CompletionItem.KIND_FUNCTION => "function",
        CompletionItem.KIND_VARIABLE => "variable",
        CompletionItem.KIND_CLASS => "class",
        CompletionItem.KIND_INTERFACE => "interface",
        CompletionItem.KIND_MODULE => "module",
        CompletionItem.KIND_PROPERTY => "property",
        CompletionItem.KIND_SNIPPET => "snippet",
        _ => "text",
    };

    private static uint CompletionKindBadgeColor(int kind) => kind switch
    {
        CompletionItem.KIND_KEYWORD => 0xFFC678DDu,
        CompletionItem.KIND_FUNCTION => 0xFF61AFEFu,
        CompletionItem.KIND_VARIABLE => 0xFFE5C07Bu,
        CompletionItem.KIND_CLASS => 0xFFE06C75u,
        CompletionItem.KIND_INTERFACE => 0xFF56B6C2u,
        CompletionItem.KIND_MODULE => 0xFFD19A66u,
        CompletionItem.KIND_PROPERTY => 0xFF98C379u,
        CompletionItem.KIND_SNIPPET => 0xFFBE5046u,
        _ => 0xFF7A8494u,
    };

    private void ShowNotification(string message, NotificationType type = NotificationType.Info)
    {
        notificationPanel.ShowNotification(message, type);
    }

    private void ShowError(string message, Exception? exception = null)
    {
        notificationPanel.ShowError(message, exception);
    }

    private void ShowSuccess(string message)
    {
        notificationPanel.ShowSuccess(message);
    }

    private void ShowWarning(string message)
    {
        notificationPanel.ShowWarning(message);
    }

    private void ShowKeyboardShortcutsDialog()
    {
        KeyboardShortcutsDialog.Open((Window)this.VisualRoot!);
    }

    private static SolidColorBrush CreateBrush(uint argb) => new(Color.FromUInt32(argb));
}
