import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:sweeteditor/editor_core.dart' as core;
import 'package:sweeteditor/sweeteditor.dart';

import 'demo_completion_provider.dart';
import 'demo_decoration_provider.dart';
import 'demo_file_metadata.dart';

void main() {
  runApp(const SweetEditorDemoApp());
}

class SweetEditorDemoApp extends StatelessWidget {
  const SweetEditorDemoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SweetEditor Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, brightness: Brightness.dark),
      home: const EditorDemoPage(),
    );
  }
}

class EditorDemoPage extends StatefulWidget {
  const EditorDemoPage({super.key});

  @override
  State<EditorDemoPage> createState() => _EditorDemoPageState();
}

class _EditorDemoPageState extends State<EditorDemoPage> {
  static const int _styleColor = EditorTheme.styleUserBase + 1;
  static const List<MapEntry<String, String>> _sampleAssets = [
    MapEntry('example.java', 'assets/demo_shared/files/example.java'),
    MapEntry('View.java', 'assets/demo_shared/files/View.java'),
    MapEntry('example.kt', 'assets/demo_shared/files/example.kt'),
    MapEntry('example.lua', 'assets/demo_shared/files/example.lua'),
    MapEntry('nlohmann-json.hpp', 'assets/demo_shared/files/nlohmann-json.hpp'),
  ];

  late final SweetEditorController _controller;
  StreamSubscription<TextChangedEvent>? _textChangedSub;
  StreamSubscription<CursorChangedEvent>? _cursorChangedSub;
  bool _isDarkTheme = true;
  core.WrapMode _wrapMode = core.WrapMode.none;
  String _statusText = 'Ready';
  int _activeSampleIndex = 0;
  bool _isLoadingSample = false;
  int _loadRequestId = 0;
  Timer? _suggestionTimer;

  @override
  void initState() {
    super.initState();
    _controller = SweetEditorController();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      unawaited(_setupEditor());
    });
  }

  @override
  void dispose() {
    _suggestionTimer?.cancel();
    _textChangedSub?.cancel();
    _cursorChangedSub?.cancel();
    super.dispose();
  }

  Future<void> _setupEditor() async {
    final settings = _controller.settings;
    settings.setFoldArrowMode(core.FoldArrowMode.auto_);
    settings.setCurrentLineRenderMode(core.CurrentLineRenderMode.border);
    settings.setMaxGutterIcons(1);

    _controller.addCompletionProvider(DemoCompletionProvider());
    try {
      await DemoDecorationProvider.ensureSweetLineReady();
      _controller.addDecorationProvider(DemoDecorationProvider(_controller));
    } catch (_) {
      _updateStatus('Failed to initialize SweetLine');
    }

    _textChangedSub = _controller.onTextChanged.listen(_onTextChanged);
    _cursorChangedSub = _controller.onCursorChanged.listen(_onCursorChanged);

    _controller.setInlineSuggestionListener(
      _DemoSuggestionListener(
        onAccepted: () => _updateStatus('Accepted suggestion'),
        onDismissed: () => _updateStatus('Dismissed suggestion'),
      ),
    );
    await _loadSampleByIndex(_activeSampleIndex);
  }

  void _onTextChanged(TextChangedEvent e) {
    final changeSummary = e.changes
        .map(
          (change) =>
              '${change.range.start.line}:${change.range.start.column}'
              '-${change.range.end.line}:${change.range.end.column}'
              ' ${change.text}',
        )
        .join(', ');
    _updateStatus('${e.action?.name ?? 'unknown'} [$changeSummary]');
  }

  void _onCursorChanged(CursorChangedEvent e) {
    _scheduleSuggestionIfAtLineEnd(e);
  }

  void _scheduleSuggestionIfAtLineEnd(CursorChangedEvent event) {
    _suggestionTimer?.cancel();
    _suggestionTimer = null;

    if (_controller.hasSelection) return;

    final line = event.cursorPosition.line;
    final column = event.cursorPosition.column;
    final lineText = _controller.getLineText(line);
    if (lineText.isEmpty ||
        column != lineText.length ||
        lineText.trim().isEmpty) {
      return;
    }

    _suggestionTimer = Timer(const Duration(seconds: 1), () {
      if (_controller.isInlineSuggestionShowing) return;
      const demoText =
          '\nvoid autoGenerated() {\n    std::cout << "hello" << std::endl;\n    return;\n}';
      _controller.showInlineSuggestion(
        InlineSuggestion(line: line, column: column, text: demoText),
      );
    });
  }

  void _toggleTheme() {
    setState(() {
      _isDarkTheme = !_isDarkTheme;
    });
    final theme = _isDarkTheme ? EditorTheme.dark() : EditorTheme.light();
    theme.defineTextStyle(
      _styleColor,
      core.TextStyle(color: _isDarkTheme ? 0xFFB5CEA8 : 0xFF098658),
    );
    _controller.setTheme(theme);
    _updateStatus(_isDarkTheme ? 'Dark theme' : 'Light theme');
  }

  void _cycleWrapMode() {
    final modes = core.WrapMode.values;
    _wrapMode = modes[(_wrapMode.value + 1) % modes.length];
    _controller.settings.setWrapMode(_wrapMode);
    _updateStatus('WrapMode: ${_wrapMode.name}');
  }

  void _updateStatus(String message) {
    if (mounted) setState(() => _statusText = message);
  }

  Future<void> _loadSampleByIndex(int index) async {
    if (index < 0 || index >= _sampleAssets.length) {
      return;
    }
    final requestId = ++_loadRequestId;
    final sample = _sampleAssets[index];
    _suggestionTimer?.cancel();
    _controller.dismissInlineSuggestion();
    _controller.dismissCompletion();
    if (mounted) {
      setState(() {
        _activeSampleIndex = index;
        _isLoadingSample = true;
      });
    }

    try {
      final text = await rootBundle.loadString(sample.value);
      if (!mounted || requestId != _loadRequestId) {
        return;
      }
      _controller.metadata = DemoFileMetadata(sample.key);
      _controller.loadText(text);
      _updateStatus('Loaded: ${sample.key}');
    } catch (e) {
      if (!mounted || requestId != _loadRequestId) {
        return;
      }
      _updateStatus('Failed to load ${sample.key}');
    } finally {
      if (mounted && requestId == _loadRequestId) {
        setState(() {
          _isLoadingSample = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = _isDarkTheme;
    final bgColor = Color(isDark ? 0xFF1B1E24 : 0xFFFAFBFD);
    final fgColor = Color(isDark ? 0xFFD7DEE9 : 0xFF1F2937);
    final secondaryColor = Color(isDark ? 0xFF5E6778 : 0xFF8A94A6);

    final theme = _isDarkTheme ? EditorTheme.dark() : EditorTheme.light();
    theme.defineTextStyle(
      _styleColor,
      core.TextStyle(color: isDark ? 0xFFB5CEA8 : 0xFF098658),
    );

    return Scaffold(
      backgroundColor: bgColor,
      body: SafeArea(
        child: Column(
          children: [
            _buildToolbar(bgColor, fgColor),
            Expanded(
              child: SweetEditorWidget(
                controller: _controller,
                theme: theme,
                fontFamily:
                    defaultTargetPlatform == TargetPlatform.iOS ||
                        defaultTargetPlatform == TargetPlatform.macOS
                    ? 'Menlo'
                    : 'monospace',
                fontSize: 14,
              ),
            ),
            _buildStatusBar(bgColor, secondaryColor),
          ],
        ),
      ),
    );
  }

  Widget _buildToolbar(Color bgColor, Color fgColor) {
    final secondaryColor = Color(_isDarkTheme ? 0xFF5E6778 : 0xFF8A94A6);
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      color: bgColor,
      child: Row(
        children: [
          Expanded(child: _buildSamplePicker(bgColor, fgColor, secondaryColor)),
          _iconButton(Icons.undo, fgColor, () {
            if (_isLoadingSample) return;
            if (_controller.canUndo) {
              _controller.undo();
              _updateStatus('Undo');
            } else {
              _updateStatus('Nothing to undo');
            }
          }),
          _iconButton(Icons.redo, fgColor, () {
            if (_isLoadingSample) return;
            if (_controller.canRedo) {
              _controller.redo();
              _updateStatus('Redo');
            } else {
              _updateStatus('Nothing to redo');
            }
          }),
          _iconButton(Icons.brightness_6, fgColor, _toggleTheme),
          _iconButton(Icons.wrap_text, fgColor, _cycleWrapMode),
        ],
      ),
    );
  }

  Widget _buildSamplePicker(
    Color bgColor,
    Color fgColor,
    Color secondaryColor,
  ) {
    return Container(
      height: 36,
      padding: const EdgeInsets.symmetric(horizontal: 10),
      alignment: Alignment.centerLeft,
      child: DropdownButtonHideUnderline(
        child: DropdownButton<int>(
          value: _activeSampleIndex,
          isExpanded: true,
          dropdownColor: bgColor,
          iconEnabledColor: secondaryColor,
          style: TextStyle(color: fgColor, fontSize: 13),
          onChanged: _isLoadingSample
              ? null
              : (value) {
                  if (value == null || value == _activeSampleIndex) {
                    return;
                  }
                  unawaited(_loadSampleByIndex(value));
                },
          items: [
            for (var i = 0; i < _sampleAssets.length; i++)
              DropdownMenuItem<int>(
                value: i,
                child: Text(
                  _sampleAssets[i].key,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
          ],
        ),
      ),
    );
  }

  Widget _iconButton(IconData icon, Color color, VoidCallback onPressed) {
    return IconButton(
      icon: Icon(icon, size: 20, color: color),
      onPressed: onPressed,
      padding: const EdgeInsets.all(6),
      constraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    );
  }

  Widget _buildStatusBar(Color bgColor, Color textColor) {
    final fileName = _sampleAssets[_activeSampleIndex].key;
    final status = _isLoadingSample ? 'Loading $fileName...' : _statusText;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      color: bgColor,
      child: Text(
        '$fileName  |  $status',
        style: TextStyle(color: textColor, fontSize: 11),
        maxLines: 1,
        overflow: TextOverflow.ellipsis,
      ),
    );
  }
}

class _DemoSuggestionListener implements InlineSuggestionListener {
  _DemoSuggestionListener({
    required this.onAccepted,
    required this.onDismissed,
  });

  final VoidCallback onAccepted;
  final VoidCallback onDismissed;

  @override
  void onSuggestionAccepted(InlineSuggestion suggestion) => onAccepted();

  @override
  void onSuggestionDismissed(InlineSuggestion suggestion) => onDismissed();
}
